#!/usr/bin/env node
/**
 * Rasterises the desktop app icons from the one source of truth,
 * `admin/brand/icon.svg`.
 *
 *   node scripts/generate-icons.js [--force]
 *
 * Outputs (all gitignored -- build output, not source):
 *   apps/desktop/resources/icon.svg   source SVG plus a generated-file notice;
 *                                     index.html uses it as the dev favicon
 *   apps/desktop/resources/icon.png   512x512, the Linux/AppImage icon and the
 *                                     BrowserWindow icon
 *   apps/desktop/resources/icon.ico   multi-size Windows icon
 *
 * The web PWA / favicon set is NOT produced here. `apps/web` generates its own
 * into `public/icons/` from the same source SVG, on its prebuild:client hook.
 * Two writers for one directory is how the committed copies went stale before.
 *
 * Rasterising uses @resvg/resvg-js, matching apps/web/scripts/generate-icons.mjs.
 * The predecessor to this script drove Playwright's Chromium, which is a ~150MB
 * browser download to produce a few KB of PNG; resvg needs no browser and no
 * network, so this step works offline.
 *
 * These files are deliberately build output rather than committed assets:
 * electron-builder reads `resources/icon.png` at package time (see the
 * `buildResources` and `extraResources` entries in electron-builder*.yml), so
 * a stale committed raster silently ships the wrong icon. On Linux the
 * BrowserWindow `icon` option is the only thing that sets the taskbar icon --
 * a missing file there falls back to Electron's default gears, which is what
 * shipped once already.
 *
 * The glyph is Font Awesome Free "book-bible" (solid), CC BY 4.0. See
 * admin/THIRD-PARTY-NOTICES.md.
 */

const fs = require('fs');
const path = require('path');
const { Resvg } = require('@resvg/resvg-js');

const ROOT = path.resolve(__dirname, '..', '..', '..');
const SOURCE_SVG = path.join(ROOT, 'admin', 'brand', 'icon.svg');
const DESKTOP_RESOURCES = path.join(ROOT, 'apps', 'desktop', 'resources');

/** Sizes packed into icon.ico. 256 is the largest an ICO directory can name. */
const ICO_SIZES = [16, 24, 32, 48, 64, 128, 256];

/** The PNG written as icon.png, and the largest entry in the .ico. */
const PNG_SIZE = 512;

// XML forbids a double hyphen inside a comment, so this notice cannot spell the
// force flag or use the repo's usual dash style.
const GENERATED_NOTICE =
  '  <!--\n' +
  '    GENERATED by scripts/generate-icons.js. Do not edit, and do not commit.\n' +
  '    The source of truth is admin/brand/icon.svg; edit that and regenerate.\n' +
  '  -->\n';

/**
 * Renders the SVG at `size`x`size` and returns the PNG bytes.
 *
 * `fitTo: { mode: 'width' }` scales the whole document to the target width
 * rather than cropping to a viewport, so the rounded corners land on exact
 * pixel boundaries at every size and the artwork is never re-laid-out.
 */
function renderPng(svg, size) {
  return new Resvg(svg, {
    fitTo: { mode: 'width', value: size },
    background: 'rgba(0,0,0,0)'
  })
    .render()
    .asPng();
}

/**
 * Packs PNG buffers into a single .ico.
 *
 * ICO layout: a 6-byte header, then one 16-byte directory entry per image,
 * then the image payloads. Modern Windows accepts PNG payloads directly
 * (rather than BMP/DIB), which is what every size here uses. A dimension of
 * 256 is encoded as 0 -- the field is one byte and 256 does not fit.
 */
function buildIco(images) {
  const header = Buffer.alloc(6);
  header.writeUInt16LE(0, 0); // reserved
  header.writeUInt16LE(1, 2); // type 1 = icon
  header.writeUInt16LE(images.length, 4);

  const directory = Buffer.alloc(16 * images.length);
  let offset = header.length + directory.length;

  images.forEach(({ size, data }, i) => {
    const entry = i * 16;
    directory.writeUInt8(size >= 256 ? 0 : size, entry + 0); // width
    directory.writeUInt8(size >= 256 ? 0 : size, entry + 1); // height
    directory.writeUInt8(0, entry + 2); // palette size (0 = truecolour)
    directory.writeUInt8(0, entry + 3); // reserved
    directory.writeUInt16LE(1, entry + 4); // colour planes
    directory.writeUInt16LE(32, entry + 6); // bits per pixel
    directory.writeUInt32LE(data.length, entry + 8);
    directory.writeUInt32LE(offset, entry + 12);
    offset += data.length;
  });

  return Buffer.concat([header, directory, ...images.map((i) => i.data)]);
}

/** Inserts the generated-file notice just after the opening <svg> tag. */
function annotate(svg) {
  return svg.replace(/(<svg\b[^>]*>)/, `$1\n${GENERATED_NOTICE}`);
}

function write(file, data) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, data);
  const bytes = Buffer.isBuffer(data) ? data.length : Buffer.byteLength(data);
  console.log(`  ${path.relative(ROOT, file).replace(/\\/g, '/')}  (${bytes} bytes)`);
}

function main() {
  const force = process.argv.includes('--force');
  const targets = ['icon.svg', 'icon.png', 'icon.ico'].map((f) =>
    path.join(DESKTOP_RESOURCES, f)
  );

  if (!force && targets.every((f) => fs.existsSync(f))) {
    console.log('[icons] Already present -- skipping (use --force to regenerate).');
    return;
  }

  const svg = fs.readFileSync(SOURCE_SVG, 'utf8');
  console.log(`Source: ${path.relative(ROOT, SOURCE_SVG).replace(/\\/g, '/')}\n`);

  // Every distinct raster size we need, rendered once and reused.
  const png = new Map();
  for (const size of [...new Set([...ICO_SIZES, PNG_SIZE])].sort((a, b) => a - b)) {
    png.set(size, renderPng(svg, size));
  }

  write(path.join(DESKTOP_RESOURCES, 'icon.svg'), annotate(svg));
  write(path.join(DESKTOP_RESOURCES, 'icon.png'), png.get(PNG_SIZE));
  write(
    path.join(DESKTOP_RESOURCES, 'icon.ico'),
    buildIco(ICO_SIZES.map((size) => ({ size, data: png.get(size) })))
  );

  console.log('\nDone.');
}

try {
  main();
} catch (err) {
  console.error(`[icons] ${err.message || err}`);
  process.exit(1);
}
