#!/usr/bin/env node
/**
 * Rasterises the app icon from the one source of truth, admin/brand/icon.svg,
 * into the PWA / favicon set under public/icons/.
 *
 * Outputs (all gitignored -- build output, not source):
 *   public/icons/icon-192.svg   source SVG at a 192 canvas, for crisp favicons
 *   public/icons/icon-512.svg   source SVG at a 512 canvas
 *   public/icons/icon-192.png   raster fallback + Android home screen
 *   public/icons/icon-512.png   raster fallback + install prompt / splash
 *
 * They are generated rather than committed: committed copies go stale the
 * moment the brand SVG is edited, and nothing notices. index.html and the PWA
 * manifest in vite.config.ts both reference these paths.
 *
 * Rasterising uses @resvg/resvg-js (Rust, prebuilt binaries) rather than a
 * headless browser: driving Playwright's Chromium means a ~150MB browser
 * download to produce 13KB of PNG. resvg needs no
 * browser and no network, so unlike the font fetch this step works offline.
 *
 * Idempotent -- existing outputs are left alone. Pass --force to regenerate.
 *
 * Usage:
 *   node scripts/generate-icons.mjs [--force]
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Resvg } from '@resvg/resvg-js';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const packageRoot = resolve(scriptDir, '..');
const SOURCE_SVG = resolve(packageRoot, '../../admin/brand/icon.svg');
const ICONS_DIR = join(packageRoot, 'public', 'icons');
const SIZES = [192, 512];

// XML forbids a double hyphen inside a comment, so this notice cannot spell the
// force flag or use the repo's usual dash style.
const GENERATED_NOTICE =
  '  <!--\n' +
  '    GENERATED by apps/web/scripts/generate-icons.mjs. Do not edit, and do not\n' +
  '    commit. Edit admin/brand/icon.svg instead, then re-run that script.\n' +
  '\n' +
  '    The glyph is the Font Awesome Free "book-bible" icon (solid) by Fonticons,\n' +
  '    Inc. (https://fontawesome.com), licensed CC BY 4.0\n' +
  '    (https://creativecommons.org/licenses/by/4.0/). Modified: recoloured and\n' +
  '    composited onto a background tile. See admin/THIRD-PARTY-NOTICES.md.\n' +
  '  -->';

/**
 * Returns the source SVG with its own header comment swapped for the generated
 * notice, and the canvas resized. The viewBox is deliberately left alone: it
 * defines the coordinate space the glyph is drawn in, so only width/height
 * change between the two sizes.
 */
function svgAtSize(source, size) {
  const withoutComment = source.replace(/^\s*<!--[\s\S]*?-->\n/m, '');
  // Tested rather than inferred from whether the string changed: at the source's
  // own size the replacement is a legitimate no-op, which that check misread as
  // a parse failure.
  const dimensions = /^(<svg\b[^>]*?)\swidth="\d+"\sheight="\d+"/m;
  if (!dimensions.test(withoutComment)) {
    throw new Error('Could not find width/height on the <svg> element of admin/brand/icon.svg');
  }
  const resized = withoutComment.replace(dimensions, `$1 width="${size}" height="${size}"`);
  return resized.replace(/^(<svg\b[^>]*>\n)/m, `$1${GENERATED_NOTICE}\n`);
}

function main() {
  if (!existsSync(SOURCE_SVG)) {
    throw new Error(`Brand icon not found at ${SOURCE_SVG}`);
  }

  const outputs = SIZES.flatMap((size) => [
    join(ICONS_DIR, `icon-${size}.svg`),
    join(ICONS_DIR, `icon-${size}.png`),
  ]);
  if (outputs.every(existsSync) && !process.argv.includes('--force')) {
    console.log('[icons] Already present -- skipping (use --force to regenerate).');
    return;
  }

  mkdirSync(ICONS_DIR, { recursive: true });
  const source = readFileSync(SOURCE_SVG, 'utf-8');

  for (const size of SIZES) {
    const svg = svgAtSize(source, size);
    writeFileSync(join(ICONS_DIR, `icon-${size}.svg`), svg);

    // Rasterise from the resized SVG so the PNG and the SVG cannot disagree.
    const png = new Resvg(svg, { fitTo: { mode: 'width', value: size } }).render().asPng();
    writeFileSync(join(ICONS_DIR, `icon-${size}.png`), png);

    console.log(`[icons] icon-${size}.svg + icon-${size}.png (${png.length} bytes)`);
  }
  console.log(`[icons] Wrote ${ICONS_DIR}`);
}

try {
  main();
} catch (err) {
  console.error(`[icons] ${err.message}`);
  process.exit(1);
}
