-- Tag Graph Module Database Schema
-- Database: tag_graph[_abbreviation].db
-- Purpose: Biblical entity graph - people, places, objects, themes, their attributes,
--          their relationships/associations, and the passages that evidence them
-- Version: 0.1.0
-- Generated: 2026-07-24
--
-- ============================================================================
-- STATUS: implemented but not shipped -- built code, no built data
-- ============================================================================
-- This is a real schema with a real consumer, not a sketch of a future feature.
-- What exists today:
--
--   * A full read path -- `TagGraphRepository` / `ITagGraphRepository`, entity
--     models, desktop IPC handlers, and web API routes.
--   * A full write path -- `scripts/build-tag-graph.js` plus the
--     `enrich-tag-graph-*` scripts that populate and audit the result.
--   * `tag_graph` as a first-class value in `MODULE_TYPES`.
--
-- What does not exist: a built `tag_graph.db`. None is generated by the normal
-- build, none is bundled with the app, and none is offered by any repository.
-- The feature is consequently dark at runtime, by two independent mechanisms:
--
--   * Web: gated behind the site-config flag `features.tagGraph`, which
--     defaults to FALSE (`SiteConfig.ts` requires an explicit `=== true`).
--   * Desktop: no flag. It simply probes for `tag_graph.db` and degrades to a
--     null repository when the file is missing -- which it always is.
--
-- So treat this file as ACTIVE-BUT-UNPOPULATED. Change it as you would any
-- other schema, because working code compiles against it and the build scripts
-- emit exactly this shape; but do not assume any user or test fixture has a
-- database in this shape to migrate, and expect every runtime read path to be
-- returning null today. If you are here because a query "does nothing", the
-- cause is almost certainly the absent file or the default-off flag, not the
-- schema.
--
-- History: this schema had no schema file before v2. Its DDL lived only inside
-- `scripts/build-tag-graph.js` (with `entity_verses` additionally created by
-- `scripts/enrich-tag-graph-verses.js`). Promoted here.
--
-- Entity identity is TEXT (slugs such as 'david', 'mount_sinai'). That is deliberate:
-- the taxonomy JSON sources, the polymorphic association columns, and the repository's
-- category->table dispatch all key on it, and every entity table therefore exposes the
-- same `id` / `name` / `notes` column trio. Category values stay plural
-- ('people','places','objects','themes') because they are DATA, not table names.
--
-- Range convention (normative): `verse_id_start` inclusive, `verse_id_end` inclusive,
-- a single verse is expressed as `verse_id_end = verse_id_start`, never as NULL.
-- Never `start_verse_id`/`end_verse_id`.

-- ============================================================================
-- Pragmas and Initialization
-- ============================================================================

PRAGMA foreign_keys = ON;
PRAGMA journal_mode = WAL;
PRAGMA synchronous = NORMAL;
PRAGMA temp_store = MEMORY;
PRAGMA cache_size = -32000;  -- 32MB cache

-- For this module type the writer sets module_type = 'tag_graph' and
-- format = 'tag-graph-module'.
-- @include ../shared/module_info.sql

-- ============================================================================
-- THE FOUR-FAMILY PATTERN (sections 1-4)
-- ============================================================================
-- People, places, objects and themes are modelled identically, so the tables in
-- sections 1-4 repeat one shape four times. Learn it once:
--
--   <family>                 The entity itself. `id` is a slug, `name` is the
--                            display label, `notes` is prose for a reader.
--   <family>_alias           Alternate names that should resolve to the entity
--                            ("Saul of Tarsus" -> paul). Many per entity.
--   <family>_attribute       A self-nesting taxonomy of properties, its own rows
--   (person_role for people) referencing their `parent_id`.
--   <family>_attribute_map   Which entities carry which attributes. A join
--   (person_role_map)        table; its composite PRIMARY KEY is the whole row.
--
-- Two conventions hold throughout:
--
--   * Every `id` is TEXT -- a stable, human-readable slug ('david',
--     'mount_sinai'), not a number. The taxonomy JSON sources use slugs, the
--     polymorphic association columns store them, and the repository dispatches
--     on category -> table with them. A rebuild of the graph therefore produces
--     the same ids, so links into it survive.
--   * `parent_id` self-references make each taxonomy a tree of arbitrary depth,
--     walked with a recursive CTE. NULL parent = a root.
--
-- Only the per-family extras differ, and those carry their own comments below:
-- person has tribe/nation, place has modern_name, object has significance.

-- ============================================================================
-- 1. People
-- ============================================================================
-- v1 -> v2: person_roles -> person_role, people -> person, people_aliases ->
--           person_alias, people_roles -> person_role_map,
--           people_relationships -> person_relationship

-- 1.1 Role taxonomy (self-nesting: 'prophet' -> 'major_prophet')
CREATE TABLE person_role (
    id        TEXT PRIMARY KEY,                     -- Role slug: 'prophet', 'major_prophet'
    name      TEXT NOT NULL,                        -- Display label: "Major Prophet"
    parent_id TEXT REFERENCES person_role(id),      -- Broader role. NULL = a root of the taxonomy.
    notes     TEXT                                  -- Prose describing the role
);

-- 1.2 People
CREATE TABLE person (
    id       TEXT PRIMARY KEY,                      -- Slug: 'david', 'mary_mother_of_jesus'
    name     TEXT NOT NULL,                         -- Primary display name. Other names for the same
                                                    -- person are person_alias rows, not extra people.
    tribe    TEXT,                                  -- Israelite tribe, where the text names one:
                                                    -- 'judah', 'levi'. NULL for non-Israelites and
                                                    -- wherever scripture is silent.
    nation   TEXT,                                  -- People-group or nation: 'israel', 'moab'. Free
                                                    -- text, not a FK to `place`: a nation is not the
                                                    -- same thing as a location.
    notes    TEXT,                                  -- Prose about the person
    metadata TEXT                                   -- JSON: anything not modelled above
);

CREATE INDEX idx_person_name ON person(name COLLATE NOCASE);

-- 1.3 Alternate names ("Saul of Tarsus" -> paul)
CREATE TABLE person_alias (
    person_id TEXT NOT NULL REFERENCES person(id),  -- The person this name refers to
    alias     TEXT NOT NULL                         -- The alternate name. Indexed COLLATE NOCASE
                                                    -- below, so lookup is case-insensitive.
);

CREATE INDEX idx_person_alias_person ON person_alias(person_id);
CREATE INDEX idx_person_alias_alias ON person_alias(alias COLLATE NOCASE);

-- 1.4 Role assignment
CREATE TABLE person_role_map (
    person_id TEXT NOT NULL REFERENCES person(id),  -- Who holds the role
    role_id   TEXT NOT NULL REFERENCES person_role(id),  -- Which role. Many-to-many: a person may hold
                                                    -- several, and the pair is the whole row.

    PRIMARY KEY (person_id, role_id)
);

-- 1.5 Person-to-person relationships (father_of, wife_of, ...)
CREATE TABLE person_relationship (
    id                           TEXT PRIMARY KEY,  -- Relationship slug
    person_1_id                  TEXT NOT NULL REFERENCES person(id),  -- The subject: read the row as
                                                    -- "person_1 is <relationship_type> person_2".
    person_2_id                  TEXT NOT NULL REFERENCES person(id),  -- The object. Order matters --
                                                    -- reading the other way needs
                                                    -- relationship_type_reciprocal.
    relationship_type            TEXT NOT NULL,     -- How person_1 stands to person_2. A genuinely
                                                    -- OPEN set: no CHECK and no fixed TypeScript list,
                                                    -- because scripture's kinship vocabulary is wider
                                                    -- than any enum worth freezing. Tokens are
                                                    -- lower_snake_case. Shipped vocabulary:
                                                    --   Family    'father_of', 'mother_of', 'son_of',
                                                    --             'daughter_of', 'husband_of',
                                                    --             'wife_of', 'brother_of',
                                                    --             'sister_of', 'ancestor_of',
                                                    --             'descendant_of'
                                                    --   Social    'servant_of', 'master_of',
                                                    --             'disciple_of', 'teacher_of',
                                                    --             'ally_of', 'enemy_of',
                                                    --             'successor_of'
                                                    -- Direction matters -- 'father_of' read the other
                                                    -- way is relationship_type_reciprocal.
    relationship_type_reciprocal TEXT,              -- Type as read from person 2 to person 1
    confidence                   TEXT,              -- How firmly scripture establishes the
                                                    -- relationship. Open set, no CHECK:
                                                    --   'certain'   Stated plainly in the text
                                                    --   'probable'  Strongly implied
                                                    --   'possible'  Supportable but not established
                                                    --   'disputed'  Interpreters disagree
                                                    --   'derived'   Inferred by the build, not by a
                                                    --               reader -- machine-generated
                                                    -- NULL = unrated, not 'certain'.
    notes                        TEXT                -- Prose, typically the passage establishing it
);

CREATE INDEX idx_person_relationship_p1 ON person_relationship(person_1_id);
CREATE INDEX idx_person_relationship_p2 ON person_relationship(person_2_id);

-- ============================================================================
-- 2. Places
-- ============================================================================
-- v1 -> v2: place_attributes -> place_attribute, places -> place,
--           place_aliases -> place_alias, place_attribute_map (unchanged)

-- 2.1 Attribute taxonomy (self-nesting: 'settlement' -> 'walled_city')
CREATE TABLE place_attribute (
    id        TEXT PRIMARY KEY,                     -- Attribute slug: 'settlement', 'walled_city'
    name      TEXT NOT NULL,                        -- Display label: "Walled City"
    parent_id TEXT REFERENCES place_attribute(id),  -- Broader attribute. NULL = a root.
    notes     TEXT                                  -- Prose describing the attribute
);

-- 2.2 Places (self-nesting: 'canaan' -> 'judea' -> 'bethlehem')
CREATE TABLE place (
    id          TEXT PRIMARY KEY,                   -- Slug: 'bethlehem', 'mount_sinai'
    name        TEXT NOT NULL,                      -- Biblical name, as scripture gives it
    parent_id   TEXT REFERENCES place(id),          -- Containing place ('judea' for 'bethlehem').
                                                    -- Geographic containment, not political history.
    modern_name TEXT,                               -- Present-day name where identification is
                                                    -- reasonably settled. NULL when disputed or
                                                    -- unknown -- common, so never rely on it.
    notes       TEXT,                               -- Prose about the place
    metadata    TEXT                                -- JSON: anything not modelled above
);

CREATE INDEX idx_place_name ON place(name COLLATE NOCASE);
CREATE INDEX idx_place_parent ON place(parent_id);

-- 2.3 Alternate names
CREATE TABLE place_alias (
    place_id TEXT NOT NULL REFERENCES place(id),  -- The place this name refers to
    alias    TEXT NOT NULL                          -- The alternate name; indexed COLLATE NOCASE below
);

CREATE INDEX idx_place_alias_place ON place_alias(place_id);
CREATE INDEX idx_place_alias_alias ON place_alias(alias COLLATE NOCASE);

-- 2.4 Attribute assignment
CREATE TABLE place_attribute_map (
    place_id     TEXT NOT NULL REFERENCES place(id),    -- Which place
    attribute_id TEXT NOT NULL REFERENCES place_attribute(id),  -- Which attribute it carries. Many-to-
                                                    -- many; the pair is the whole row.

    PRIMARY KEY (place_id, attribute_id)
);

-- ============================================================================
-- 3. Objects
-- ============================================================================
-- v1 -> v2: object_attributes -> object_attribute, objects -> object,
--           object_aliases -> object_alias, object_attribute_map (unchanged)

-- 3.1 Attribute taxonomy
CREATE TABLE object_attribute (
    id        TEXT PRIMARY KEY,                     -- Attribute slug: 'tabernacle_furnishing'
    name      TEXT NOT NULL,                        -- Display label: "Tabernacle Furnishing"
    parent_id TEXT REFERENCES object_attribute(id),  -- Broader attribute. NULL = a root.
    notes     TEXT                                  -- Prose describing the attribute
);

-- 3.2 Objects (self-nesting: 'tabernacle_furnishing' -> 'ark_of_the_covenant')
CREATE TABLE object (
    id           TEXT PRIMARY KEY,                  -- Slug: 'ark_of_the_covenant'
    name         TEXT NOT NULL,                     -- Display name
    parent_id    TEXT REFERENCES object(id),        -- Containing or superordinate object. NULL = a root.
    significance TEXT,                              -- The object's role in the text -- an editorial
                                                    -- judgement, not a physical property. Open set,
                                                    -- no CHECK:
                                                    --   'mundane'     Ordinary object, no special
                                                    --                 weight (a lamp, a jar)
                                                    --   'symbolic'    Carries figurative meaning
                                                    --                 (the vine, the yoke)
                                                    --   'sacred'      Set apart for worship (the ark,
                                                    --                 the altar)
                                                    --   'miraculous'  Involved in a miracle (Aaron's
                                                    --                 rod, the bronze serpent)
                                                    -- NULL = unclassified.
    notes        TEXT,                              -- Prose about the object
    metadata     TEXT                               -- JSON: anything not modelled above
);

CREATE INDEX idx_object_name ON object(name COLLATE NOCASE);
CREATE INDEX idx_object_parent ON object(parent_id);

-- 3.3 Alternate names
CREATE TABLE object_alias (
    object_id TEXT NOT NULL REFERENCES object(id),  -- The object this name refers to
    alias     TEXT NOT NULL                          -- The alternate name; indexed COLLATE NOCASE below
);

CREATE INDEX idx_object_alias_object ON object_alias(object_id);
CREATE INDEX idx_object_alias_alias ON object_alias(alias COLLATE NOCASE);

-- 3.4 Attribute assignment
CREATE TABLE object_attribute_map (
    object_id    TEXT NOT NULL REFERENCES object(id),    -- Which object
    attribute_id TEXT NOT NULL REFERENCES object_attribute(id),  -- Which attribute it carries. Many-to-
                                                    -- many; the pair is the whole row.

    PRIMARY KEY (object_id, attribute_id)
);

-- ============================================================================
-- 4. Themes
-- ============================================================================
-- v1 -> v2: theme_attributes -> theme_attribute, themes -> theme,
--           theme_aliases -> theme_alias, theme_attribute_map (unchanged),
--           theme_traditions -> theme_tradition

-- 4.1 Attribute taxonomy
CREATE TABLE theme_attribute (
    id        TEXT PRIMARY KEY,                     -- Attribute slug: 'soteriology'
    name      TEXT NOT NULL,                        -- Display label: "Soteriology"
    parent_id TEXT REFERENCES theme_attribute(id),  -- Broader attribute. NULL = a root.
    notes     TEXT                                  -- Prose describing the attribute
);

-- 4.2 Themes (self-nesting: 'covenant' -> 'new_covenant')
CREATE TABLE theme (
    id        TEXT PRIMARY KEY,                     -- Slug: 'covenant', 'new_covenant'
    name      TEXT NOT NULL,                        -- Display name
    parent_id TEXT REFERENCES theme(id),            -- Broader theme. NULL = a root.
    notes     TEXT,                                 -- Prose about the theme
    metadata  TEXT                                  -- JSON: anything not modelled above
);

CREATE INDEX idx_theme_name ON theme(name COLLATE NOCASE);
CREATE INDEX idx_theme_parent ON theme(parent_id);

-- 4.3 Alternate names
CREATE TABLE theme_alias (
    theme_id TEXT NOT NULL REFERENCES theme(id),  -- The theme this name refers to
    alias    TEXT NOT NULL                          -- The alternate name; indexed COLLATE NOCASE below
);

CREATE INDEX idx_theme_alias_theme ON theme_alias(theme_id);
CREATE INDEX idx_theme_alias_alias ON theme_alias(alias COLLATE NOCASE);

-- 4.4 Attribute assignment
CREATE TABLE theme_attribute_map (
    theme_id     TEXT NOT NULL REFERENCES theme(id),    -- Which theme
    attribute_id TEXT NOT NULL REFERENCES theme_attribute(id),  -- Which attribute it carries. Many-to-
                                                    -- many; the pair is the whole row.

    PRIMARY KEY (theme_id, attribute_id)
);

-- 4.5 Traditions that emphasize a theme (open set: 'reformed', 'catholic', ...)
CREATE TABLE theme_tradition (
    theme_id  TEXT NOT NULL REFERENCES theme(id),   -- The theme
    tradition TEXT NOT NULL,                        -- Tradition that gives it particular weight. Open
                                                    -- set, no CHECK: 'reformed', 'catholic',
                                                    -- 'orthodox', 'lutheran', 'anabaptist',
                                                    -- 'wesleyan', 'dispensational'. Says a
                                                    -- tradition EMPHASIZES the theme -- not that it
                                                    -- owns it, and not that others reject it.

    PRIMARY KEY (theme_id, tradition)
);

-- ============================================================================
-- 5. Cross-Entity Associations
-- ============================================================================
-- v1 -> v2: association_types -> association_type,
--           association_type_category_pairs -> association_type_category_pair,
--           tag_associations -> tag_association

-- 5.1 Association vocabulary (born_in, dwelt_in, authored, ...)
CREATE TABLE association_type (
    id              TEXT PRIMARY KEY,               -- Type slug: 'born_in', 'authored'
    name            TEXT NOT NULL,                  -- Label read entity_1 -> entity_2: "born in"
    reciprocal_name TEXT,                           -- Label when read in the other direction
                                                    -- ("birthplace of"). Just wording.
    reciprocal_id   TEXT REFERENCES association_type(id),  -- The type that IS this one reversed, when a
                                                    -- distinct type exists for it. Distinct from
                                                    -- reciprocal_name, which only renames this type;
                                                    -- self-referential for symmetric types.
    notes           TEXT                            -- Prose describing the association type
);

-- 5.2 Which category pairs a type is valid for ('people' x 'places', ...)
CREATE TABLE association_type_category_pair (
    association_type_id TEXT NOT NULL REFERENCES association_type(id),  -- The type being constrained
    entity_1_category   TEXT NOT NULL,              -- Allowed category of the subject end:
                                                    -- people|places|objects|themes
    entity_2_category   TEXT NOT NULL,              -- Allowed category of the object end. 'born_in'
                                                    -- admits ('people','places') and nothing else.
                                                    -- Advisory only -- tag_association has no FK to
                                                    -- this table; scripts/validate-module.js checks it.

    PRIMARY KEY (association_type_id, entity_1_category, entity_2_category)
);

-- 5.3 The association edges themselves.
-- Polymorphic: (entity_N_category, entity_N_id) points at person/place/object/theme.
-- No FK is possible on a polymorphic reference; integrity is checked by
-- scripts/validate-module.js.
CREATE TABLE tag_association (
    id                  TEXT PRIMARY KEY,           -- Edge slug. entity_verse_link rows cite it as
                                                    -- source_id with source_type='tag_association'.
    entity_1_id         TEXT NOT NULL,              -- Subject end: the slug. Which TABLE it lives in is
                                                    -- decided by entity_1_category -- the two columns
                                                    -- are one polymorphic reference and no FK can
                                                    -- express it.
    entity_1_category   TEXT NOT NULL,              -- people|places|objects|themes (open set, validated
                                                    -- in TypeScript). Plural, because it names a
                                                    -- category as DATA, not a table.
    entity_2_id         TEXT NOT NULL,              -- Object end: the slug
    entity_2_category   TEXT NOT NULL,              -- Object end: its category, as above
    association_type_id TEXT REFERENCES association_type(id),  -- What kind of edge. NULL for an
                                                    -- association the builder found but could not
                                                    -- classify -- e.g. bare co-occurrence.
    strength            REAL CHECK (strength BETWEEN 0.0 AND 1.0),  -- How strongly the two are linked,
                                                    -- 0.0-1.0. Closed numeric domain, so the CHECK is
                                                    -- kept. Distinct from `confidence`: strength is how
                                                    -- STRONG the link is, confidence is how SURE we are
                                                    -- it exists. A co-occurrence may be certain and
                                                    -- weak; an inference, strong and disputed.
    confidence          TEXT,                       -- How sure we are the association is real (as
                                                    -- opposed to `strength` above -- see it). Open set,
                                                    -- no CHECK, same vocabulary as
                                                    -- person_relationship.confidence:
                                                    --   'certain'   Stated plainly in the text
                                                    --   'probable'  Strongly implied
                                                    --   'possible'  Supportable but not established
                                                    --   'disputed'  Interpreters disagree
                                                    --   'derived'   Inferred by the build, not by a
                                                    --               reader -- machine-generated
    source              TEXT,                       -- What produced the row. Open set, no CHECK:
                                                    --   'seeded'        Authored by hand in the
                                                    --                   taxonomy JSON sources
                                                    --   'cooccurrence'  Derived by build-tag-graph.js
                                                    --                   from entities appearing in the
                                                    --                   same passages
                                                    --   'llm'           Proposed by enrich-tag-graph-
                                                    --                   llm.js
                                                    -- Lets a consumer show or hide machine-derived
                                                    -- edges. Pairs with `confidence`: a 'cooccurrence'
                                                    -- edge is typically 'derived'.
    notes               TEXT,                       -- Prose about the association
    metadata            TEXT                        -- JSON: anything not modelled above
);

CREATE INDEX idx_tag_association_e1 ON tag_association(entity_1_id, entity_1_category);
CREATE INDEX idx_tag_association_e2 ON tag_association(entity_2_id, entity_2_category);
CREATE INDEX idx_tag_association_type ON tag_association(association_type_id);

-- ============================================================================
-- 6. Topical Index Integration
-- ============================================================================
-- v1 -> v2: entity_topic_links -> entity_topic_link, entity_facets -> entity_facet,
--           entity_facet_members -> entity_facet_member
--
-- `source_module` + `topic_id` are a SOFT cross-database reference into a topical
-- index module (topical_*.db, table `topic`). There is no FK across databases;
-- `source_module` holds the topical module's abbreviation.

-- 6.1 Entity -> topic mapping produced by name/alias matching
CREATE TABLE entity_topic_link (
    entity_id       TEXT NOT NULL,                  -- Entity slug; polymorphic with entity_category
    entity_category TEXT NOT NULL,                  -- people|places|objects|themes (open set, validated
                                                    -- in TypeScript)
    source_module   TEXT NOT NULL,                  -- Topical module identifier ('topical_nave')
    topic_id        INTEGER NOT NULL,               -- topic.topic_id in that module
    match_type      TEXT NOT NULL,                  -- HOW the entity was matched to the topic, so a
                                                    -- weak match can be shown differently from a firm
                                                    -- one. Not a confidence score. Open set, no CHECK:
                                                    --   'exact'  Entity `name` equalled the topic name
                                                    --   'alias'  An <entity>_alias row matched
                                                    --   'stem'   Matched only after stemming --
                                                    --            the loosest, and the most likely to
                                                    --            be a false positive

    PRIMARY KEY (entity_id, source_module, topic_id)
);

CREATE INDEX idx_entity_topic_link_entity ON entity_topic_link(entity_id, entity_category);
CREATE INDEX idx_entity_topic_link_topic ON entity_topic_link(source_module, topic_id);

-- 6.2 Structural subtopic groups hanging off an entity
-- ("Kings of Judah" as a facet of the entity 'judah')
CREATE TABLE entity_facet (
    facet_id               INTEGER PRIMARY KEY,     -- Assigned by the builder, not autoincrement
    parent_entity_id       TEXT NOT NULL,           -- Entity the facet hangs off ('judah'), by slug
    parent_entity_category TEXT NOT NULL,           -- Its category; polymorphic, as everywhere else
    facet_label            TEXT NOT NULL,           -- Normalized label
    facet_display_label    TEXT NOT NULL,           -- Label as shown in the UI
    source_module          TEXT NOT NULL,           -- Topical module abbreviation
    source_topic_id        INTEGER NOT NULL,        -- topic.topic_id in that module
    metadata               TEXT                     -- JSON: anything not modelled above
);

CREATE INDEX idx_entity_facet_parent ON entity_facet(parent_entity_id, parent_entity_category);

-- 6.3 Entities that belong to a facet
CREATE TABLE entity_facet_member (
    facet_id               INTEGER NOT NULL REFERENCES entity_facet(facet_id),  -- The group
    member_entity_id       TEXT NOT NULL,           -- Member entity's slug
    member_entity_category TEXT NOT NULL,           -- Its category. A facet may mix categories.
    source_topic_id        INTEGER,                 -- The topic in the source module that produced this
                                                    -- membership, where one did. NULL for a member
                                                    -- added by other means.
    sort_order             INTEGER NOT NULL DEFAULT 0,  -- Display order within the facet

    PRIMARY KEY (facet_id, member_entity_id)
);

CREATE INDEX idx_entity_facet_member_facet ON entity_facet_member(facet_id);

-- ============================================================================
-- 7. Verse Linking
-- ============================================================================

-- Byte-identical in every module schema and in the user database. It is the table a
-- generic consumer or the format validator looks for. In a tag graph it carries links
-- whose source row has an INTEGER key - currently `entity_facet` (source_type=
-- 'entity_facet', source_id=facet_id); the graph's own entity and association links
-- are textual and live in `entity_verse_link` below.
--
-- In a tag graph this table carries only the links whose owner has an INTEGER
-- key -- currently source_type = 'entity_facet', source_id = entity_facet.facet_id.
-- Entity and association links have TEXT keys and live in `entity_verse_link`.
-- @include ../shared/verse_link.sql

-- 7.2 Entity verse links (textual source identity).
-- Identical in shape and conventions to `verse_link` except that `source_id` is TEXT,
-- because tag-graph entities and associations are keyed by slug. This ONE table
-- replaces BOTH v1 verse-linking shapes:
--
--     entity_verses.entity_id        -> entity_verse_link.source_id
--     entity_verses.entity_category  -> entity_verse_link.source_type
--                                       ('people'|'places'|'objects'|'themes')
--     entity_verses.start_verse_id   -> entity_verse_link.verse_id_start
--     entity_verses.end_verse_id     -> entity_verse_link.verse_id_end
--                                       (v1 wrote 0 for "single verse" on text-search
--                                        rows; v2 requires NULL)
--     entity_verses.source           -> entity_verse_link.provenance ('topical','text_search')
--
--     association_verses.association_id -> entity_verse_link.source_id
--                                          (source_type='tag_association')
--     association_verses.start_verse_id -> entity_verse_link.verse_id_start
--     association_verses.end_verse_id   -> entity_verse_link.verse_id_end
--     association_verses.source_module  -> entity_verse_link.provenance
--     association_verses.sort_order     -> entity_verse_link.sort_order
CREATE TABLE entity_verse_link (
    link_id         INTEGER PRIMARY KEY AUTOINCREMENT,  -- Row id; nothing references it
    source_type     TEXT NOT NULL,   -- 'people','places','objects','themes','tag_association'.
                                     -- Note the entity values are CATEGORIES, not table names --
                                     -- unlike verse_link, where source_type IS a table name.
    source_id       TEXT NOT NULL,   -- Entity slug or tag_association.id. TEXT: the whole reason
                                     -- this table exists alongside verse_link.
    verse_id_start  INTEGER NOT NULL, -- Target passage, inclusive
    verse_id_end    INTEGER NOT NULL, -- inclusive; single verse is expressed as end = start
    link_type       TEXT NOT NULL DEFAULT 'reference',  -- Kind of pointing, same open set as
                                     -- verse_link.link_type (LINK_TYPES in Data/Core/Types.ts):
                                     -- 'reference' (default), 'primary_passage', 'annotation',
                                     -- 'cross_reference'. No CHECK -- see the note below the indexes.
    sort_order      INTEGER NOT NULL DEFAULT 0,  -- Display order among one owner's links
    provenance      TEXT,            -- What produced this link: 'topical', 'text_search',
                                     -- or a module identifier such as 'topical_nave'.
                                     -- Part of the dedup key below, so two routes finding the
                                     -- same verse stay two rows -- deliberately, since it is
                                     -- corroboration. COALESCE'd there: NULL is one value.
    context         TEXT,            -- Freeform note carried with this one link
    metadata        TEXT             -- JSON: anything not modelled above
);

CREATE INDEX idx_entity_verse_link_source ON entity_verse_link(source_type, source_id, sort_order);
CREATE INDEX idx_entity_verse_link_start  ON entity_verse_link(verse_id_start);
CREATE INDEX idx_entity_verse_link_range  ON entity_verse_link(verse_id_start, verse_id_end);

-- Preserves the deduplication that the v1 composite PRIMARY KEYs provided
-- (entity_verses: entity_id+entity_category+start_verse_id+source;
--  association_verses: association_id+start_verse_id). COALESCE keeps rows with a
-- NULL provenance from being treated as distinct.
CREATE UNIQUE INDEX idx_entity_verse_link_unique
    ON entity_verse_link(source_type, source_id, verse_id_start, COALESCE(provenance, ''));

-- no CHECK on source_type or link_type in either table. Both are
-- open/extensible sets; validation lives in TypeScript
-- (packages/core/src/Data/Core/Types.ts) and is enforced at the repository boundary.

-- ============================================================================
-- 8. Schema Version
-- ============================================================================

-- @include ../shared/schema_version.sql

INSERT INTO schema_version (version_number, notes)
VALUES ('0.1.0', 'Initial release.');
