/**
 * Public extension API surface - the contract every extension worker speaks.
 *
 * Spec A section "Public extension API surface". This file defines the
 * `BibleExtensionAPI` interface (the root object the host injects into each
 * extension worker) plus every namespace interface beneath it.
 *
 * All methods are async and return JSON-serializable values. No class
 * instances cross the API boundary, no synchronous calls, no DOM access from
 * the worker. The corresponding host implementations live in
 * `apps/desktop/electron/extensions/api-impl/`.
 *
 * DTOs imported from `./ExtensionApiDtos` are deliberately separated so the
 * shape definitions (T1 foundation work) can be reviewed and locked
 * independently of the methods that consume them.
 */

import type {
  BackgroundTaskDescriptor,
  BackgroundTaskInfo,
  BibleBookDto,
  BibleModuleInfoDto,
  BibleProviderDescriptor,
  BibleVerseDto,
  BookIterationResult,
  BookModuleInfoDto,
  BookProviderDescriptor,
  BookSectionDto,
  BookSectionSummaryDto,
  BookmarkDto,
  CollectionDto,
  CommentaryEntryDto,
  CommentaryIterationResult,
  CommentaryModuleInfoDto,
  CommentaryProviderDescriptor,
  ConfirmOpts,
  ContextMenuItemDescriptor,
  ContextMenuTarget,
  DecorationDto,
  DictionaryEntryDto,
  DictionaryIterationResult,
  DictionaryModuleInfoDto,
  DictionaryProviderDescriptor,
  DisplayModeDescriptor,
  DisposableHandle,
  ExtensionCommandRegistration,
  ExtensionPanelTypeDef,
  ExtensionProviderInfo,
  FileInfo,
  FolderGrantHandle,
  FolderUsageInfo,
  HighlightStyleDescriptor,
  IEventApi,
  IExtensionDatabase,
  InputBoxOpts,
  IterateBookOpts,
  IterateCommentaryOpts,
  IterateDictionaryOpts,
  IterateVersesOpts,
  LocalizedString,
  NetworkFetchInit,
  NetworkFetchResponse,
  NewHighlightDto,
  NewNoteDto,
  NoteQueryDto,
  NotificationOpts,
  OAuthResult,
  OpenDatabaseOpts,
  OpenPanelOpts,
  PanelInfoDto,
  ParsedReferenceDto,
  PickFileOpts,
  PickedFileDto,
  QuickPickItemDescriptor,
  QuickPickOpts,
  RefreshOAuthOpts,
  SaveFileOpts,
  StartOAuthOpts,
  StatusBarItemDescriptor,
  TaskProgressUpdate,
  UserHighlightDto,
  UserNoteDto,
  VerseDecoratorDescriptor,
  VerseHoverProviderDescriptor,
  VerseIterationResult,
  VerseTokenDto,
  VerseWordSelection,
  WhenContextValue,
} from './ExtensionApiDtos';

/**
 * The current extension API version. Used by the host and worker to negotiate
 * compatibility (see `engines.bibleApp` in the manifest and Spec A
 * section "API versioning"). Bumped according to strict semver:
 *
 * - **Patch**: bug fixes only. No surface change.
 * - **Minor**: additive only - new methods, optional fields, permissions,
 *   contribution points, extension points, provider roles.
 * - **Major**: breaking change. Ships side-by-side with the previous major
 *   for at least 12 months.
 */
export const EXTENSION_API_VERSION = '1.0.0' as const;

/**
 * Root API object the host injects into each extension worker. The worker
 * receives an instance of this in its `activate(api)` entry point.
 *
 * Each namespace below is a thin RPC proxy generated by
 * `apps/desktop/extension-runtime/apiProxy.ts` - calling
 * `api.bible.getVerse(...)` from the worker emits an `RpcRequest` envelope
 * that the host's `ExtensionRpcRouter` dispatches to
 * `bibleApiImpl.getVerse(...)` after the permission guard runs.
 */
export interface BibleExtensionAPI {
  bible: IBibleApi;
  commentary: ICommentaryApi;
  book: IBookApi;
  dictionary: IDictionaryApi;
  notes: INotesApi;
  highlights: IHighlightsApi;
  bookmarks: IBookmarksApi;
  commands: ICommandsApi;
  ui: IUiApi;
  workspace: IWorkspaceApi;
  context: IContextApi;
  storage: IStorageApi;
  l10n: IL10nApi;
  events: IEventsApi;
  /** T2 - outbound HTTP, host-mediated. */
  network: INetworkApi;
  /** T2 - OAuth 2.0 / PKCE broker. */
  auth: IAuthApi;
  /** T2 - background tasks with progress. */
  tasks: ITasksApi;
  /** T2 - inter-extension method calls. */
  extensions: IExtensionsApi;
  /** RESERVED - provider-role plumbing only in v1. */
  ai: IAiApi;
}

// --- IBibleApi *(T1 - read methods are foundation; iterate/tokens are T2)* -

export interface IBibleApi {
  /** Get a single verse from the active or specified module. */
  getVerse(verseId: number, opts?: { module?: string }): Promise<BibleVerseDto>;

  /** Get a range of verses (inclusive). Max range size: 500 verses. */
  getRange(
    start: number,
    end: number,
    opts?: { module?: string },
  ): Promise<BibleVerseDto[]>;

  /** List installed Bible modules with metadata. */
  listModules(): Promise<BibleModuleInfoDto[]>;

  /** List the books in a Bible module (with chapter counts). */
  listBooks(moduleId?: string): Promise<BibleBookDto[]>;

  /**
   * Cursor-based iteration across verses. Required for extensions that need
   * to scan the corpus (custom indexes, embeddings, alignment data). Max page
   * size is 1000; the host may return fewer than requested. The host
   * guarantees stable iteration order across calls with the same opts.
   */
  iterateVerses(opts: IterateVersesOpts): Promise<VerseIterationResult>;

  /** Parse a reference string. Locale-aware. */
  parseReference(input: string, locale?: string): Promise<ParsedReferenceDto | null>;

  /**
   * Get token-level data for a verse if the module exposes it (interlinear,
   * Strong's, morphology). Returns null if the module has no token data.
   */
  getVerseTokens(
    verseId: number,
    opts?: { module?: string },
  ): Promise<VerseTokenDto[] | null>;

  /**
   * Programmatically navigate the primary Bible pane to a specific verse.
   * The host resolves after the renderer has processed the navigation
   * request and fires `onDidChangeActiveVerse` once the verse is visible.
   *
   * Requires `bible:read` permission (navigation is a read-adjacent action).
   */
  navigateToVerse(verseId: number): Promise<void>;

  /**
   * Register a custom Bible text provider. The host treats it as another
   * installed module. Requires `bible:provide` permission.
   */
  registerProvider(
    provider: BibleProviderDescriptor,
  ): Promise<DisposableHandle>;

  /** Stable event: the user navigated to a new active verse anywhere in the app. */
  onDidChangeActiveVerse: IEventApi<{ verseId: number; module: string } | null>;

  /** A token / word inside a verse was selected (click, double-click, or selection). */
  onDidSelectVerseWord: IEventApi<VerseWordSelection>;
}

// --- ICommentaryApi *(T1 reads; provider/iterate are T2)* ------------------

export interface ICommentaryApi {
  listModules(): Promise<CommentaryModuleInfoDto[]>;
  getEntry(moduleId: string, verseId: number): Promise<CommentaryEntryDto | null>;

  /**
   * Get all entries that touch a verse range. Useful for "show all commentary
   * on Romans 8" or for building an index.
   */
  getEntriesForRange(
    moduleId: string,
    startVerseId: number,
    endVerseId: number,
  ): Promise<CommentaryEntryDto[]>;

  /** Cursor-based iteration over all entries in a module. */
  iterateEntries(opts: IterateCommentaryOpts): Promise<CommentaryIterationResult>;

  /** Register a custom commentary provider. The host treats it as another module. */
  registerProvider(
    provider: CommentaryProviderDescriptor,
  ): Promise<DisposableHandle>;

  onDidChangeActiveCommentary: IEventApi<{ moduleId: string } | null>;
}

// --- IDictionaryApi *(T1 reads; provider/iterate are T2)* ------------------

export interface IDictionaryApi {
  listModules(): Promise<DictionaryModuleInfoDto[]>;

  /** Look up a single entry by its key (Strong's number, lemma, or headword). */
  lookup(moduleId: string, key: string): Promise<DictionaryEntryDto | null>;

  /** Free-text search. */
  search(
    moduleId: string,
    query: string,
    opts?: { limit?: number },
  ): Promise<DictionaryEntryDto[]>;

  /** Cursor-based iteration over all entries. */
  iterateEntries(opts: IterateDictionaryOpts): Promise<DictionaryIterationResult>;

  /**
   * Register a custom dictionary provider - e.g. a paid lexicon, an online
   * API, or a richer Greek/Hebrew lookup with stemming and morphology data.
   */
  registerProvider(
    provider: DictionaryProviderDescriptor,
  ): Promise<DisposableHandle>;

  onDidChangeActiveDictionary: IEventApi<{ moduleId: string } | null>;
}

// --- IBookApi *(T1 reads; provider/iterate are T2)* ------------------------

export interface IBookApi {
  listModules(): Promise<BookModuleInfoDto[]>;

  /** Get a single section by id. */
  getSection(moduleId: string, sectionId: string): Promise<BookSectionDto | null>;

  /** Get the table of contents (or a subtree) for a book module. */
  listSections(
    moduleId: string,
    parentId?: string,
  ): Promise<BookSectionSummaryDto[]>;

  /** Cursor-based iteration over all sections (depth-first). */
  iterateSections(opts: IterateBookOpts): Promise<BookIterationResult>;

  registerProvider(provider: BookProviderDescriptor): Promise<DisposableHandle>;

  onDidChangeActiveBook: IEventApi<{ moduleId: string } | null>;
}

// --- INotesApi / IHighlightsApi / IBookmarksApi *(T1 CRUD; styles are T2)* -

export interface INotesApi {
  list(query?: NoteQueryDto): Promise<UserNoteDto[]>;
  get(id: string): Promise<UserNoteDto | null>;
  create(note: NewNoteDto): Promise<UserNoteDto>;
  update(id: string, patch: Partial<UserNoteDto>): Promise<UserNoteDto>;
  delete(id: string): Promise<void>;
  onDidChange: IEventApi<{ id: string; type: 'created' | 'updated' | 'deleted' }>;
}

export interface IHighlightsApi {
  list(verseId?: number): Promise<UserHighlightDto[]>;
  create(highlight: NewHighlightDto): Promise<UserHighlightDto>;
  update(id: string, patch: Partial<NewHighlightDto>): Promise<UserHighlightDto>;
  delete(id: string): Promise<void>;

  /**
   * Register a custom highlight style. The style appears in the user's
   * highlight picker and persists across sessions. Styles can target whole
   * verses, ranges, or sub-verse word ranges.
   */
  registerStyle(style: HighlightStyleDescriptor): Promise<DisposableHandle>;

  /** List all registered highlight styles (built-in + extension-contributed). */
  listStyles(): Promise<HighlightStyleDescriptor[]>;

  onDidChange: IEventApi<{ verseId: number }>;
}

export interface IBookmarksApi {
  list(collectionId?: string): Promise<BookmarkDto[]>;
  add(verseId: number, collectionId?: string): Promise<BookmarkDto>;
  remove(id: string): Promise<void>;
  listCollections(): Promise<CollectionDto[]>;
  createCollection(name: LocalizedString): Promise<CollectionDto>;
}

// --- ICommandsApi *(T1)* ---------------------------------------------------

/**
 * Thin proxy over Spec B's `ICommandRegistry`. The extension worker calls it;
 * the host translates each call into a `commandRegistry.register({ ... handler:
 * rpcCallback })` where `rpcCallback` issues a reverse RPC back into the
 * worker on invocation.
 *
 * Aliases are intentionally absent - extensions handle their own aliases via
 * their locale catalogs.
 */
export interface ICommandsApi {
  register(cmd: ExtensionCommandRegistration): Promise<DisposableHandle>;
  execute(commandId: string, args?: unknown): Promise<unknown>;
}

// --- IUiApi *(T1 panels/decorators/hovers/menus/notifications;
//             T2 displayMode/statusBar/file picker/updateDecorations)* -----

export interface IUiApi {
  /** Contribute a new panel/content type. */
  registerPanelType(def: ExtensionPanelTypeDef): Promise<DisposableHandle>;

  /** Contribute a verse decorator. */
  registerVerseDecorator(d: VerseDecoratorDescriptor): Promise<DisposableHandle>;

  /**
   * Update an existing decoration group (matched by `groupId`). Use this when
   * data behind a decoration changes - e.g. a stemming overlay rebuilds.
   */
  updateVerseDecorations(
    groupId: string,
    decorations: DecorationDto[],
  ): Promise<void>;

  /** Contribute hover content for verses. */
  registerVerseHover(
    h: VerseHoverProviderDescriptor,
  ): Promise<DisposableHandle>;

  /** Add an item to a built-in context menu. */
  registerContextMenu(
    target: ContextMenuTarget,
    item: ContextMenuItemDescriptor,
  ): Promise<DisposableHandle>;

  /**
   * Contribute a custom verse display mode. Appears in the Bible pane's
   * Display Mode picker alongside Simple/Standard/Study. The host calls
   * `renderEndpoint` for each visible verse, and the extension returns
   * either decorations to overlay on the standard rendering, or an iframe
   * URL to fully replace the verse's rendering.
   */
  registerDisplayMode(def: DisplayModeDescriptor): Promise<DisposableHandle>;

  /**
   * Contribute a status bar item. Useful for "X items indexed", "Connected
   * to logos.com", etc.
   */
  registerStatusBarItem(
    item: StatusBarItemDescriptor,
  ): Promise<DisposableHandle>;

  /** Show a non-modal toast. */
  showNotification(msg: LocalizedString, opts?: NotificationOpts): Promise<void>;

  /**
   * Show a quick-pick prompt. The promise resolves with the user's selection
   * or undefined.
   */
  showQuickPick<T>(
    items: QuickPickItemDescriptor<T>[],
    opts?: QuickPickOpts,
  ): Promise<T | undefined>;

  /** Show a single-line input prompt. */
  showInputBox(opts: InputBoxOpts): Promise<string | undefined>;

  /** Show a modal confirm dialog. */
  showConfirm(opts: ConfirmOpts): Promise<boolean>;

  /**
   * Open the system file picker for the user to choose a file. Requires
   * `fs:read-user`. The host returns the file contents (not the path) so the
   * extension never sees absolute paths.
   */
  pickFile(opts?: PickFileOpts): Promise<PickedFileDto | undefined>;

  /** Open the system save picker. Requires `fs:write-user`. */
  saveFile(
    content: string | ArrayBuffer | Uint8Array,
    opts?: SaveFileOpts,
  ): Promise<boolean>;
}

// --- IWorkspaceApi *(T1)* --------------------------------------------------

export interface IWorkspaceApi {
  getActivePanel(): Promise<PanelInfoDto | null>;
  getOpenPanels(): Promise<PanelInfoDto[]>;
  /** Returns the panelId. */
  openPanel(contentType: string, opts?: OpenPanelOpts): Promise<string>;
  closePanel(panelId: string): Promise<void>;
  onDidChangeActivePanel: IEventApi<PanelInfoDto | null>;
  onDidOpenPanel: IEventApi<PanelInfoDto>;
  onDidClosePanel: IEventApi<{ panelId: string; contentType: string }>;
}

// --- IContextApi *(T1)* ----------------------------------------------------

export interface IContextApi {
  /** Read a context key (built-in or extension-namespaced). */
  get(key: string): Promise<WhenContextValue | undefined>;

  /**
   * Set an extension-namespaced context key. Throws on attempts to set
   * built-in keys (only `ext.<id>.*` keys are writable from extensions).
   */
  set(key: string, value: WhenContextValue): Promise<void>;

  onDidChange: IEventApi<{ keys: string[] }>;
}

// --- IStorageApi *(T1 KV/secrets/settings; T2 openDatabase)* ---------------

/**
 * Backed by the `extension_storage` SQLite table. The host auto-prefixes the
 * extension ID; extensions cannot read each other's keys.
 *
 * Quotas:
 * - **KV tier:** default 5 MB per extension. Exceeding throws
 *   `QuotaExceededError`. Configurable in Preferences.
 * - **Database tier:** no hard quota by default - extensions that opt in via
 *   `storage:database` are expected to need real space (indexes, embeddings,
 *   custom corpora). The Extensions UI shows per-extension disk usage and
 *   lets the user set a per-extension cap if desired.
 * - **Secrets:** no quota; OS keychain limits apply.
 */
export interface IStorageApi {
  // ---- KV (small) ----
  get<T = unknown>(key: string): Promise<T | undefined>;
  set(key: string, value: unknown): Promise<void>;
  delete(key: string): Promise<void>;
  keys(): Promise<string[]>;

  // ---- Secrets (OS keychain) ----
  /** Routes through the OS keychain (keytar) for sensitive values. */
  setSecret(key: string, value: string): Promise<void>;
  getSecret(key: string): Promise<string | undefined>;
  deleteSecret(key: string): Promise<void>;

  // ---- Settings (read-only mirror of contributes.configuration) ----
  /**
   * Read a user-edited setting defined in `contributes.configuration`. The
   * host populates these from the rendered settings form. Equivalent to
   * `get('__settings.<key>')` but type-safe against the schema.
   */
  getSetting<T = unknown>(key: string): Promise<T | undefined>;
  onDidChangeSettings: IEventApi<{ keys: string[] }>;

  // ---- Per-extension SQLite database ----
  /**
   * Open a SQLite database file owned by this extension. The file lives at
   * `data/extensions/<id>/db/<name>.db`. Use this for indexes, embeddings,
   * or any data that exceeds the KV tier. Requires the `storage:database`
   * permission. The host opens the file with WAL mode and foreign keys on.
   *
   * The database is created on first open. The host runs no migrations -
   * the extension is responsible for its own schema. The host backs the
   * file up with the rest of user data unless the extension marks it
   * ephemeral via `opts`.
   */
  openDatabase(
    name: string,
    opts?: OpenDatabaseOpts,
  ): Promise<IExtensionDatabase>;

  /** Approximate disk usage of all storage owned by this extension, in bytes. */
  diskUsage(): Promise<{ kv: number; databases: number; secretsCount: number }>;

  // ---- Managed folder (desktop-only, large files) ----

  /**
   * Request a user-chosen folder for scoped file storage. The host opens a
   * folder picker dialog; if the user selects a folder the grant is persisted
   * so it survives extension restarts. Returns `null` if the user cancelled.
   * Requires the `fs:managed-folder` permission.
   *
   * @param purpose - Human-readable reason shown in the folder picker dialog.
   */
  requestFolder(purpose: string): Promise<FolderGrantHandle | null>;

  /**
   * Get the current folder grant, if one exists. Returns `null` if no grant
   * has been made or if it was revoked. Requires `fs:managed-folder`.
   */
  getFolderGrant(): Promise<FolderGrantHandle | null>;

  /**
   * Revoke the current folder grant. The files on disk are NOT deleted - only
   * the extension's access is removed. Requires `fs:managed-folder`.
   */
  revokeFolderGrant(): Promise<void>;

  /**
   * Read a file inside the granted folder. The `path` is relative to the
   * grant root and must not escape it. Requires `fs:managed-folder`.
   */
  readFile(path: string): Promise<ArrayBuffer>;

  /**
   * Write (or overwrite) a file inside the granted folder. The `path` is
   * relative to the grant root. Parent directories are created automatically.
   * Requires `fs:managed-folder`.
   */
  writeFile(path: string, data: ArrayBuffer | Uint8Array): Promise<void>;

  /**
   * Delete a file inside the granted folder. No-op if the file does not
   * exist. Requires `fs:managed-folder`.
   */
  deleteFile(path: string): Promise<void>;

  /**
   * List files and directories inside the granted folder, optionally
   * filtered by a relative path prefix. Requires `fs:managed-folder`.
   */
  listFiles(prefix?: string): Promise<FileInfo[]>;

  /**
   * Get metadata for a single file inside the granted folder. Returns `null`
   * if the file does not exist. Requires `fs:managed-folder`.
   */
  statFile(path: string): Promise<FileInfo | null>;

  /**
   * Get aggregate disk usage for the granted folder. Requires
   * `fs:managed-folder`.
   */
  getFolderUsage(): Promise<FolderUsageInfo>;
}

// --- IL10nApi *(T1)* -------------------------------------------------------

/**
 * Extension catalogs ship in `l10n/<bcp47>.json` files inside the extension
 * package. The host loads them into Spec B's `I18nService` under a namespace
 * prefixed with the extension ID, so `ext.greekTools.openLexicon` resolves to
 * the extension's own catalog.
 */
export interface IL10nApi {
  /** Resolve a localization key against the extension's catalog. */
  t(key: string, params?: Record<string, unknown>): Promise<string>;

  // Maintainer note: this was declared `currentLocale: Promise<string>`, which
  // cannot work. `api` is an RPC proxy, so reading a property yields a
  // *function* that would dispatch the call, and awaiting a function is not an
  // error - it resolves to the function. Callers following the old declaration
  // silently got a function where a locale string was promised. The host has
  // always implemented the `l10n.currentLocale` method this signature
  // describes. `ApiSurfaceContract.test.ts` now rejects bare data properties.
  /** The host's current UI locale, e.g. `'en'` or `'pt-BR'`. */
  currentLocale(): Promise<string>;
  onDidChangeLocale: IEventApi<string>;
}

// --- IEventsApi *(T1)* -----------------------------------------------------

/**
 * Wraps the cross-cutting subscription model so extensions can subscribe to
 * host-emitted hook events (the ~30 hooks listed in `ExtensionPointTypes.ts`).
 *
 * The host wraps every emit with a try/catch and a 2-second timeout per
 * subscriber; a slow or throwing subscriber gets its handle disposed with a
 * logged warning, but never blocks the host or other subscribers.
 */
export interface IEventsApi {
  subscribe<T>(
    channel: ExtensionPointId,
    handler: (payload: T) => void | Promise<void>,
  ): Promise<DisposableHandle>;
}

/**
 * String literal union of every host-emitted extension point. Payload and
 * return types live in `ExtensionPointTypes.ts`.
 */
export type ExtensionPointId =
  // Verse rendering and interaction
  | 'verse.beforeRender'
  | 'verse.afterRender'
  | 'verse.hover'
  | 'verse.contextMenu'
  | 'verse.word.contextMenu'
  | 'verse.decorate'
  | 'verse.activeChanged'
  | 'verse.wordSelected'
  | 'verse.beforeFormat'
  // Content modules
  | 'commentary.providerRegistered'
  | 'commentary.beforeShow'
  | 'commentary.similarRequested'
  | 'dictionary.lookupRequested'
  | 'dictionary.beforeShow'
  | 'book.beforeShow'
  | 'crossReferences.requested'
  // Notes / highlights / bookmarks
  | 'notes.beforeSave'
  | 'notes.afterSave'
  | 'notes.beforeDelete'
  | 'highlights.afterChange'
  | 'bookmarks.afterAdd'
  // Search
  | 'search.beforeQuery'
  | 'search.afterResults'
  | 'search.suggestionsRequested'
  // Workspace and lifecycle
  | 'panel.opened'
  | 'panel.closed'
  | 'panel.focused'
  | 'layout.presetApplied'
  | 'bible.referenceParsed'
  | 'command.beforeExecute'
  | 'app.ready'
  | 'session.restored'
  | 'theme.changed'
  | 'locale.changed'
  | 'settings.changed'
  | 'permissions.changed'
  // Modules and extensions
  | 'module.installed'
  | 'module.updated'
  | 'module.removed'
  | 'extension.activated'
  | 'extension.deactivated';

// --- INetworkApi *(T2)* ----------------------------------------------------

export interface INetworkApi {
  /**
   * Mediated outbound HTTP/HTTPS request. The URL's host MUST appear in the
   * extension's `network.allowedHosts` manifest entry; otherwise the call
   * rejects with `NetworkHostNotAllowedError` even if `network` permission is
   * granted.
   *
   * Private-network destinations (loopback, RFC1918, link-local) are blocked
   * by default. To target a private host, the extension must list a literal
   * IP or hostname in `allowedHosts` and the user must approve it explicitly
   * at install time (the consent dialog highlights private targets).
   */
  fetch(url: string, init?: NetworkFetchInit): Promise<NetworkFetchResponse>;

  /** True if the host is currently in the extension's allowlist. */
  isHostAllowed(host: string): Promise<boolean>;
}

// --- IAuthApi *(T2 - depends on INetworkApi)* ------------------------------

export interface IAuthApi {
  /**
   * Run the OAuth 2.0 Authorization Code flow (with PKCE by default). The
   * host opens a real BrowserWindow pointing at `authorizeUrl`, watches for
   * navigation to the redirect URI, captures the `code` and `state`, performs
   * the token exchange itself, and resolves with the result.
   *
   * The redirect URI is always `ext-ui://<extensionId>/<redirectPath>`,
   * registered with the auth provider. This means the host's custom protocol
   * receives the redirect - no public callback server required.
   *
   * Token storage is the extension's responsibility (use `storage:secrets`).
   */
  startOAuth(opts: StartOAuthOpts): Promise<OAuthResult>;

  /** Exchange a refresh_token for a new access_token. */
  refreshOAuth(opts: RefreshOAuthOpts): Promise<OAuthResult>;

  /**
   * Open the user's default browser at a URL (e.g. for a settings page on
   * the extension's website). Requires `network:oauth` permission.
   */
  openExternal(url: string): Promise<void>;
}

// --- ITasksApi *(T2)* ------------------------------------------------------

export interface ITasksApi {
  /**
   * Run a long-running task. The host invokes `workEndpoint` via reverse-RPC
   * with a `taskHandle` the worker uses to report progress and check for
   * cancellation. The host shows a progress entry in the status bar and a
   * notification on completion if `notifyOnComplete` is set.
   */
  run<T = void>(task: BackgroundTaskDescriptor): Promise<T>;

  /** Report progress for a running task. Called from inside the work handler. */
  reportProgress(taskHandle: string, update: TaskProgressUpdate): Promise<void>;

  /** True if the user has requested cancellation. The work handler should return early. */
  isCancellationRequested(taskHandle: string): Promise<boolean>;

  /** Cancel a running task by ID. */
  cancel(taskId: string): Promise<void>;

  /** List tasks owned by this extension. */
  list(): Promise<BackgroundTaskInfo[]>;
}

// --- IExtensionsApi *(T2)* -------------------------------------------------

/**
 * The narrow surface (no events, no streaming) is intentional. If two
 * extensions need a tighter coupling, they can both depend on a third
 * extension that owns the shared state.
 */
export interface IExtensionsApi {
  /**
   * Call a method another extension has exported via `contributes.apiExports`.
   * Requires `extensions:call` permission. The host validates the call against
   * the callee's manifest - undeclared methods reject with
   * `ApiExportNotFoundError`.
   *
   * Calls are mediated by the host (worker A -> host -> worker B) so neither
   * extension can crash the other. Arguments and return values must be
   * JSON-serializable.
   */
  call<T = unknown>(
    extensionId: string,
    method: string,
    args?: unknown[],
  ): Promise<T>;

  /** True if an extension is installed and active. */
  isActive(extensionId: string): Promise<boolean>;

  /** List extensions that export at least one API method. */
  listProviders(): Promise<ExtensionProviderInfo[]>;

  onDidActivate: IEventApi<{ extensionId: string }>;
  onDidDeactivate: IEventApi<{ extensionId: string }>;
}

// --- IAiApi (RESERVED) *(T1 stub - full surface is T3)* --------------------

/**
 * RESERVED in v1. The permission slot, manifest field, and provider role
 * (`aiAssistant`) exist so extensions and the host can plan around AI
 * integration without breaking the API contract later. The host UI for
 * "Ask AI about this verse" lives in a follow-up spec.
 *
 * Extensions that want to ship AI features in v1 should use `INetworkApi` to
 * call their own AI backend; the only thing missing is the host's built-in
 * panel for displaying AI responses.
 */
export interface IAiApi {
  /** True if the host has any active AI provider. Always false in v1. */
  isAvailable(): Promise<boolean>;
}
