/**
 * Public extension API surface - the contract every extension worker speaks.
 *
 * This file defines the
 * `BibleExtensionAPI` interface (the root object the host injects into each
 * extension worker) plus every namespace interface beneath it.
 *
 * All methods are async and return JSON-serializable values. No class
 * instances cross the API boundary, no synchronous calls, no DOM access from
 * the worker. The corresponding host implementations live in
 * `apps/desktop/electron/extensions/api-impl/`.
 *
 * DTOs imported from `./ExtensionApiDtos` are deliberately separated so the
 * shape definitions (T1 foundation work) can be reviewed and locked
 * independently of the methods that consume them.
 */

import type {
  BackgroundTaskDescriptor,
  BackgroundTaskInfo,
  BibleBookDto,
  BibleChapterDto,
  BibleModuleInfoDto,
  BibleProviderDescriptor,
  BibleVerseDto,
  BookIterationResult,
  BookModuleInfoDto,
  BookProviderDescriptor,
  BookSectionDto,
  BookSectionSummaryDto,
  BookmarkDto,
  CollectionDto,
  CommentaryEntryDto,
  CommentaryIterationResult,
  CommentaryModuleInfoDto,
  CommentaryProviderDescriptor,
  ConfirmOpts,
  ContextMenuItemDescriptor,
  ContextMenuTarget,
  DecorationDto,
  DictionaryEntryDto,
  DictionaryIterationResult,
  DictionaryModuleInfoDto,
  DictionaryProviderDescriptor,
  DisposableHandle,
  ExtensionCommandRegistration,
  ExtensionPanelTypeDef,
  ExtensionProviderInfo,
  FileInfo,
  FolderGrantHandle,
  FolderUsageInfo,
  HighlightStyleDescriptor,
  IExtensionDatabase,
  InputBoxOpts,
  IterateBookOpts,
  IterateCommentaryOpts,
  IterateDictionaryOpts,
  IterateVersesOpts,
  LocalizedString,
  NetworkFetchInit,
  NetworkFetchResponse,
  NewCollectionOpts,
  NewHighlightDto,
  NewNoteDto,
  NewPassageDto,
  NoteQueryDto,
  NotificationOpts,
  OAuthResult,
  OpenDatabaseOpts,
  OpenPanelOpts,
  PanelInfoDto,
  PanelMessageSender,
  ParsedReferenceDto,
  PassageCollectionDto,
  PassageEntryDto,
  PickFileOpts,
  PickedFileDto,
  QuickPickItemDescriptor,
  QuickPickOpts,
  RefreshOAuthOpts,
  SaveFileOpts,
  StartOAuthOpts,
  StatusBarItemDescriptor,
  TaskProgressUpdate,
  UserHighlightDto,
  UserNoteDto,
  VerseDecoratorDescriptor,
  VerseHoverProviderDescriptor,
  VerseIterationResult,
  VerseTokenDto,
  WhenContextValue,
} from './ExtensionApiDtos';
import type {
  ExtensionPointPayloadMap,
  ExtensionPointReturnMap,
} from './ExtensionPointTypes';

/**
 * The current extension API version. Used by the host and worker to negotiate
 * compatibility (see `engines.bibleApp` in the manifest).
 *
 * **Retrograded to `0.1.0` (task 0024, round 3).** Earlier work on this task
 * bumped this through `1.1.0` and `1.2.0` under a strict-semver policy
 * (patch/minor/major, with a 12-month major dual-support window). The human
 * reviewing round 3 pointed out that policy assumes a stable, publicly
 * distributed API - which does not exist yet: no beta has shipped, and the
 * only extension written against this API (`bible-memory`) is written by the
 * same person approving this task. Resetting to a pre-1.0, unstable-by-
 * definition `0.1.0` says plainly that nothing here is a compatibility
 * promise yet, and removes the temptation to read a `1.x`/`2.x` number as
 * one. (The human suggested the bare string "0.1" - this file uses `0.1.0`
 * instead because `semverRange.ts`'s `parseVersion` requires a strict
 * three-segment `\d+.\d+.\d+`, and `engines.bibleApp` range matching against
 * `EXTENSION_API_VERSION` would otherwise silently fail to parse and refuse
 * every extension. `0.1.0` is the three-segment form of the same version.)
 *
 * The strict-semver / 12-month-dual-support policy above is retired along
 * with the number; it can be reinstated verbatim once a real beta or public
 * release makes versioning promises meaningful. Until then, treat every
 * change - additive or breaking - as pre-release churn: bump the middle
 * segment (`0.2.0`, `0.3.0`, ...) for any surface change worth noting in an
 * extension's `engines.bibleApp` range, and do not read more into the number
 * than that.
 *
 * This round's breaking changes (the `onDid*` -> `api.events.subscribe`
 * unification below) ship under this same `0.1.0` - there is no
 * dual-support window to honor, and `bible-memory` is updated in lockstep in
 * its own task.
 */
export const EXTENSION_API_VERSION = '0.1.0' as const;

/**
 * Root API object the host injects into each extension worker. The worker
 * receives an instance of this in its `activate(api)` entry point.
 *
 * Each namespace below is a thin RPC proxy generated by
 * `apps/desktop/extension-runtime/apiProxy.ts` - calling
 * `api.bible.getVerse(...)` from the worker emits an `RpcRequest` envelope
 * that the host's `ExtensionRpcRouter` dispatches to
 * `bibleApiImpl.getVerse(...)` after the permission guard runs.
 */
export interface BibleExtensionAPI {
  bible: IBibleApi;
  commentary: ICommentaryApi;
  book: IBookApi;
  dictionary: IDictionaryApi;
  notes: INotesApi;
  highlights: IHighlightsApi;
  bookmarks: IBookmarksApi;
  /** Ordered lists of passages - reading plans, outlines, memorisation sets. */
  collections: ICollectionsApi;
  commands: ICommandsApi;
  ui: IUiApi;
  workspace: IWorkspaceApi;
  context: IContextApi;
  storage: IStorageApi;
  l10n: IL10nApi;
  events: IEventsApi;
  /**
   * Binds this extension's callbacks to the reverse-RPC endpoints the host
   * calls back on. Worker-local: nothing here crosses to the host.
   */
  runtime: IRuntimeApi;
  /** Messages from this extension's own panel iframes. */
  panels: IPanelsApi;
  /** T2 - outbound HTTP, host-mediated. */
  network: INetworkApi;
  /** T2 - OAuth 2.0 / PKCE broker. */
  auth: IAuthApi;
  /** T2 - background tasks with progress. */
  tasks: ITasksApi;
  /** T2 - inter-extension method calls. */
  extensions: IExtensionsApi;
  /** RESERVED - provider-role plumbing only in v1. */
  ai: IAiApi;
}

// --- IBibleApi *(T1 - read methods are foundation; iterate/tokens are T2)* -

export interface IBibleApi {
  /** Get a single verse from the active or specified module. */
  getVerse(verseId: number, opts?: { module?: string }): Promise<BibleVerseDto>;

  /** Get a range of verses (inclusive). Max range size: 500 verses. */
  getRange(
    start: number,
    end: number,
    opts?: { module?: string },
  ): Promise<BibleVerseDto[]>;

  /** List installed Bible modules with metadata. */
  listModules(): Promise<BibleModuleInfoDto[]>;

  /** List the books in a Bible module (with chapter counts). */
  listBooks(moduleId?: string): Promise<BibleBookDto[]>;

  /**
   * List every chapter of one book with its verse count and its inclusive
   * verse-id bounds. Ordered by chapter; `length` is the book's chapter count.
   *
   * This is how a passage range is resolved. `collections.addPassage` requires a
   * `verseIdEnd`, and nothing else on this surface can tell you where a chapter
   * stops - `listBooks` gives chapter counts but not verse counts, and paging
   * `iterateVerses` to the end of a chapter reads the entire chapter to learn a
   * single number. One call per book rather than one per chapter, because the
   * callers that need this ("add John to my reading plan", "outline Psalms")
   * almost always want the whole book, and 150 small records is cheaper than
   * 150 round trips.
   *
   * Resolves to an empty array for a book the host has no versification data
   * for. A `bookNumber` outside the 66-book canon is a caller bug, not a
   * missing book, and rejects.
   */
  listChapters(bookNumber: number, moduleId?: string): Promise<BibleChapterDto[]>;

  /**
   * Cursor-based iteration across verses. Required for extensions that need
   * to scan the corpus (custom indexes, embeddings, alignment data). Max page
   * size is 1000; the host may return fewer than requested. The host
   * guarantees stable iteration order across calls with the same opts.
   */
  iterateVerses(opts: IterateVersesOpts): Promise<VerseIterationResult>;

  /** Parse a reference string. Locale-aware. */
  parseReference(input: string, locale?: string): Promise<ParsedReferenceDto | null>;

  /**
   * Get token-level data for a verse if the module exposes it (interlinear,
   * Strong's, morphology). Returns null if the module has no token data.
   */
  getVerseTokens(
    verseId: number,
    opts?: { module?: string },
  ): Promise<VerseTokenDto[] | null>;

  /**
   * Programmatically navigate the primary Bible pane to a specific verse.
   * The host resolves after the renderer has processed the navigation
   * request and dispatches `verse.activeChanged` (`api.events.subscribe`)
   * once the verse is visible.
   *
   * Requires `bible:read` permission (navigation is a read-adjacent action).
   */
  navigateToVerse(verseId: number): Promise<void>;

  /**
   * Register a custom Bible text provider. The host treats it as another
   * installed module. Requires `bible:provide` permission.
   */
  registerProvider(
    provider: BibleProviderDescriptor,
  ): Promise<DisposableHandle>;
}

// --- ICommentaryApi *(T1 reads; provider/iterate are T2)* ------------------

export interface ICommentaryApi {
  listModules(): Promise<CommentaryModuleInfoDto[]>;
  getEntry(moduleId: string, verseId: number): Promise<CommentaryEntryDto | null>;

  /**
   * Get all entries that touch a verse range. Useful for "show all commentary
   * on Romans 8" or for building an index.
   */
  getEntriesForRange(
    moduleId: string,
    startVerseId: number,
    endVerseId: number,
  ): Promise<CommentaryEntryDto[]>;

  /** Cursor-based iteration over all entries in a module. */
  iterateEntries(opts: IterateCommentaryOpts): Promise<CommentaryIterationResult>;

  /** Register a custom commentary provider. The host treats it as another module. */
  registerProvider(
    provider: CommentaryProviderDescriptor,
  ): Promise<DisposableHandle>;
}

// --- IDictionaryApi *(T1 reads; provider/iterate are T2)* ------------------

export interface IDictionaryApi {
  listModules(): Promise<DictionaryModuleInfoDto[]>;

  /** Look up a single entry by its key (Strong's number, lemma, or headword). */
  lookup(moduleId: string, key: string): Promise<DictionaryEntryDto | null>;

  /** Free-text search. */
  search(
    moduleId: string,
    query: string,
    opts?: { limit?: number },
  ): Promise<DictionaryEntryDto[]>;

  /** Cursor-based iteration over all entries. */
  iterateEntries(opts: IterateDictionaryOpts): Promise<DictionaryIterationResult>;

  /**
   * Register a custom dictionary provider - e.g. a paid lexicon, an online
   * API, or a richer Greek/Hebrew lookup with stemming and morphology data.
   */
  registerProvider(
    provider: DictionaryProviderDescriptor,
  ): Promise<DisposableHandle>;
}

// --- IBookApi *(T1 reads; provider/iterate are T2)* ------------------------

export interface IBookApi {
  listModules(): Promise<BookModuleInfoDto[]>;

  /** Get a single section by id. */
  getSection(moduleId: string, sectionId: string): Promise<BookSectionDto | null>;

  /** Get the table of contents (or a subtree) for a book module. */
  listSections(
    moduleId: string,
    parentId?: string,
  ): Promise<BookSectionSummaryDto[]>;

  /** Cursor-based iteration over all sections (depth-first). */
  iterateSections(opts: IterateBookOpts): Promise<BookIterationResult>;

  registerProvider(provider: BookProviderDescriptor): Promise<DisposableHandle>;
}

// --- INotesApi / IHighlightsApi / IBookmarksApi *(T1 CRUD; styles are T2)* -

export interface INotesApi {
  list(query?: NoteQueryDto): Promise<UserNoteDto[]>;
  get(id: string): Promise<UserNoteDto | null>;
  create(note: NewNoteDto): Promise<UserNoteDto>;
  update(id: string, patch: Partial<UserNoteDto>): Promise<UserNoteDto>;
  delete(id: string): Promise<void>;
}

export interface IHighlightsApi {
  list(verseId?: number): Promise<UserHighlightDto[]>;
  create(highlight: NewHighlightDto): Promise<UserHighlightDto>;
  update(id: string, patch: Partial<NewHighlightDto>): Promise<UserHighlightDto>;
  delete(id: string): Promise<void>;

  /**
   * Register a custom highlight style. The style appears in the user's
   * highlight picker and persists across sessions. Styles can target whole
   * verses, ranges, or sub-verse word ranges.
   */
  registerStyle(style: HighlightStyleDescriptor): Promise<DisposableHandle>;

  /** List all registered highlight styles (built-in + extension-contributed). */
  listStyles(): Promise<HighlightStyleDescriptor[]>;
}

export interface IBookmarksApi {
  list(collectionId?: string): Promise<BookmarkDto[]>;
  add(verseId: number, collectionId?: string): Promise<BookmarkDto>;
  remove(id: string): Promise<void>;
  listCollections(): Promise<CollectionDto[]>;
  createCollection(name: LocalizedString): Promise<CollectionDto>;
}

// --- ICollectionsApi *(ordered passage lists)* -----------------------------

/**
 * Ordered lists of scripture passages: reading plans, sermon outlines,
 * memorisation sets, lectionaries.
 *
 * **Why this is not more methods on `IBookmarksApi`.** A bookmark is a flag on
 * a verse - it exists or it does not, and asking where it sits in a sequence
 * is a category error. A study list is a *sequence of ranges*, where position
 * is the point: "day 3" means the third entry, and moving it changes what the
 * user reads on Wednesday. Both live in the same `collection` /
 * `pinned_item` tables, but that is a storage fact, not a modelling one.
 * Widening `IBookmarksApi` would have produced an `add()` whose `verseId`
 * meant a point sometimes and a range's start other times, and a `list()`
 * returning items whose order was meaningful for some collections and
 * arbitrary for others - and every consumer would have inherited the job of
 * telling those apart. Two namespaces, two concepts.
 *
 * ```typescript
 * const plan = await api.collections.create('Romans in 30 days');
 * await api.collections.addPassage(plan.id, {
 *   verseIdStart: 45008028, verseIdEnd: 45008030, label: 'Day 12',
 * });
 * // Put the new entry first instead of last:
 * await api.collections.move(entry.id, 0);
 * ```
 *
 * **Permissions.** Reads require `bookmarks:read`, writes `bookmarks:write` -
 * the same grants `IBookmarksApi` uses, because these are the same rows. A
 * separate `collections:*` permission would have let an extension the user
 * refused bookmark access read and rewrite the identical table through the
 * other door, which is a permission that exists only on paper.
 *
 * **Ordering.** Positions are dense, contiguous and zero-based: a collection
 * of n entries occupies exactly 0..n-1, so an index read back from
 * `listPassages` is an index `move` accepts. Inserting mid-list shifts every
 * later entry down by one; removing shifts them up. The host renumbers the
 * whole collection in a single transaction rather than leaving gaps, so two
 * entries can never share a position and no entry can drift out of range.
 */
export interface ICollectionsApi {
  /**
   * Every collection the user has, ordered by the user's own arrangement then
   * by name. Includes collections created through the app's own UI and
   * through `bookmarks.createCollection` - there is one collection store, not
   * an extension-private one.
   */
  list(): Promise<PassageCollectionDto[]>;

  /** Create a collection. Nest it by passing `opts.parentId`. */
  create(
    name: LocalizedString,
    opts?: NewCollectionOpts,
  ): Promise<PassageCollectionDto>;

  /**
   * Rename a collection. Resolves with the updated collection so a caller
   * that renders the result does not need a follow-up `list()`.
   */
  rename(
    collectionId: string,
    name: LocalizedString,
  ): Promise<PassageCollectionDto>;

  /**
   * Delete a collection and everything in it - its passages and, because the
   * store cascades, any collections nested beneath it. Deleting a collection
   * that does not exist is an error, not a no-op: silently succeeding hides
   * the far more common case of a stale id.
   */
  delete(collectionId: string): Promise<void>;

  /**
   * The collection's passages in order, resolved: each entry carries its
   * inclusive verse range, its label, its pinned module, and a human-readable
   * `reference` string the host derives from the range.
   *
   * Returns `[]` for an empty collection and rejects for an unknown one, so a
   * caller can tell "nothing in it yet" from "wrong id".
   */
  listPassages(collectionId: string): Promise<PassageEntryDto[]>;

  /**
   * Add a passage. Appends by default; pass `passage.position` to insert at a
   * specific index, shifting later entries down.
   */
  addPassage(
    collectionId: string,
    passage: NewPassageDto,
  ): Promise<PassageEntryDto>;

  /** Remove one passage. Later entries close the gap. */
  removePassage(entryId: string): Promise<void>;

  /**
   * Move one passage to `position` within its own collection. Resolves with
   * the collection's full new ordering, which is what a UI needs to repaint
   * and saves it a round trip.
   *
   * A position past the end moves the entry last rather than rejecting -
   * "put this at the bottom" is a legitimate request that a caller should not
   * have to compute the exact index for.
   */
  move(entryId: string, position: number): Promise<PassageEntryDto[]>;

  /**
   * Replace a collection's ordering wholesale. `entryIds` must be a
   * permutation of exactly the ids currently in the collection - a partial
   * list would leave the omitted entries at positions this call did not
   * choose, which is a silent reordering nobody asked for. Resolves with the
   * new ordering.
   */
  reorder(
    collectionId: string,
    entryIds: string[],
  ): Promise<PassageEntryDto[]>;
}

// --- ICommandsApi *(T1)* ---------------------------------------------------

/**
 * Thin proxy over Spec B's `ICommandRegistry`. The extension worker calls it;
 * the host translates each call into a `commandRegistry.register({ ... handler:
 * rpcCallback })` where `rpcCallback` issues a reverse RPC back into the
 * worker on invocation.
 *
 * Aliases are intentionally absent - extensions handle their own aliases via
 * their locale catalogs.
 */
export interface ICommandsApi {
  register(cmd: ExtensionCommandRegistration): Promise<DisposableHandle>;
  execute(commandId: string, args?: unknown): Promise<unknown>;
}

// --- IUiApi *(T1 panels/decorators/hovers/menus/notifications;
//             T2 displayMode/statusBar/file picker/updateDecorations)* -----

export interface IUiApi {
  /** Contribute a new panel/content type. */
  registerPanelType(def: ExtensionPanelTypeDef): Promise<DisposableHandle>;

  /** Contribute a verse decorator. */
  registerVerseDecorator(d: VerseDecoratorDescriptor): Promise<DisposableHandle>;

  /**
   * Update an existing decoration group (matched by `groupId`). Use this when
   * data behind a decoration changes - e.g. a stemming overlay rebuilds.
   */
  updateVerseDecorations(
    groupId: string,
    decorations: DecorationDto[],
  ): Promise<void>;

  /** Contribute hover content for verses. */
  registerVerseHover(
    h: VerseHoverProviderDescriptor,
  ): Promise<DisposableHandle>;

  /** Add an item to a built-in context menu. */
  registerContextMenu(
    target: ContextMenuTarget,
    item: ContextMenuItemDescriptor,
  ): Promise<DisposableHandle>;

  /**
   * Contribute a status bar item. Useful for "X items indexed", "Connected
   * to logos.com", etc.
   */
  registerStatusBarItem(
    item: StatusBarItemDescriptor,
  ): Promise<DisposableHandle>;

  /**
   * Patch an already-registered status bar item in place. Only the fields
   * present in `patch` change; everything else - including fields the
   * original `registerStatusBarItem` call left unset - is kept. Use this
   * instead of disposing and re-registering when only the data changes
   * (e.g. a counter ticking up): re-registering the same `id` repeatedly is
   * wasteful (a full descriptor round-trip, permission check and
   * validation for one changed field) and, before this method existed, was
   * also the only way an author could avoid stacking up disposal handles.
   *
   * Rejects if `itemId` was never registered by this extension, or was
   * already disposed.
   */
  updateStatusBarItem(
    itemId: string,
    patch: Partial<Omit<StatusBarItemDescriptor, 'id'>>,
  ): Promise<void>;

  /**
   * Show a non-modal toast. Resolves with the `id` of the action the user
   * clicked, if `opts.actions` was given and they clicked one; otherwise
   * resolves `undefined` - the user dismissed it, another notification
   * replaced it, or it auto-dismissed after `opts.durationMs`.
   *
   * Awaiting the result is optional - a toast with no actions and nothing
   * awaiting it behaves exactly as it always did.
   */
  showNotification(msg: LocalizedString, opts?: NotificationOpts): Promise<string | undefined>;

  /**
   * Show a quick-pick prompt. The promise resolves with the user's selection
   * or undefined.
   */
  showQuickPick<T>(
    items: QuickPickItemDescriptor<T>[],
    opts?: QuickPickOpts,
  ): Promise<T | undefined>;

  /** Show a single-line input prompt. */
  showInputBox(opts: InputBoxOpts): Promise<string | undefined>;

  /** Show a modal confirm dialog. */
  showConfirm(opts: ConfirmOpts): Promise<boolean>;

  /**
   * Open the system file picker for the user to choose a file. Requires
   * `fs:read-user`. The host returns the file contents (not the path) so the
   * extension never sees absolute paths.
   */
  pickFile(opts?: PickFileOpts): Promise<PickedFileDto | undefined>;

  /** Open the system save picker. Requires `fs:write-user`. */
  saveFile(
    content: string | ArrayBuffer | Uint8Array,
    opts?: SaveFileOpts,
  ): Promise<boolean>;
}

// --- IWorkspaceApi *(T1)* --------------------------------------------------

export interface IWorkspaceApi {
  getActivePanel(): Promise<PanelInfoDto | null>;
  getOpenPanels(): Promise<PanelInfoDto[]>;
  /** Returns the panelId. */
  openPanel(contentType: string, opts?: OpenPanelOpts): Promise<string>;
  closePanel(panelId: string): Promise<void>;

  /**
   * Change an already-open panel's tab title. Restricted to the extension's
   * own panels - `panelId` must name a panel whose `contentType` is one of
   * this extension's own (`ext:<this extension's id>.*`). Renaming a
   * built-in tab or another extension's tab would be a spoofing vector, not
   * a legitimate UI adjustment, so this rejects with `PermissionDeniedError`
   * for anything else, or a plain error if `panelId` is not currently open.
   */
  setPanelTitle(panelId: string, title: LocalizedString): Promise<void>;

  /**
   * Set, or clear (pass `undefined`), a small badge on an already-open
   * panel's tab - e.g. a due/unread count. Same ownership rule as
   * `setPanelTitle`.
   */
  setPanelBadge(panelId: string, badge: string | number | undefined): Promise<void>;

  /**
   * Bring an already-open panel's tab to the front, without changing its
   * content. This is the "stop working around it" call for an extension
   * that owns a tab and wants a "Show in <panel>" action to land the user on
   * it, rather than only on the status bar. Unlike `setPanelTitle` /
   * `setPanelBadge` this needs no ownership check - focusing a tab is
   * exactly as visible and reversible as `openPanel` / `closePanel`, which
   * are also unrestricted.
   *
   * Resolves `true` if `panelId` was open and got focused, `false` if it was
   * not found (already closed, or never existed).
   */
  revealPanel(panelId: string): Promise<boolean>;
}

// --- IContextApi *(T1)* ----------------------------------------------------

export interface IContextApi {
  /** Read a context key (built-in or extension-namespaced). */
  get(key: string): Promise<WhenContextValue | undefined>;

  /**
   * Set an extension-namespaced context key. Throws on attempts to set
   * built-in keys (only `ext.<id>.*` keys are writable from extensions).
   */
  set(key: string, value: WhenContextValue): Promise<void>;
}

// --- IStorageApi *(T1 KV/secrets/settings; T2 openDatabase)* ---------------

/**
 * Backed by the `extension_storage` SQLite table. The host auto-prefixes the
 * extension ID; extensions cannot read each other's keys.
 *
 * Quotas:
 * - **KV tier:** default 5 MB per extension. Exceeding throws
 *   `QuotaExceededError`. Configurable in Preferences.
 * - **Database tier:** no hard quota by default - extensions that opt in via
 *   `storage:database` are expected to need real space (indexes, embeddings,
 *   custom corpora). The Extensions UI shows per-extension disk usage and
 *   lets the user set a per-extension cap if desired.
 * - **Secrets:** no quota; OS keychain limits apply.
 */
export interface IStorageApi {
  // ---- KV (small) ----
  get<T = unknown>(key: string): Promise<T | undefined>;
  set(key: string, value: unknown): Promise<void>;
  delete(key: string): Promise<void>;
  keys(): Promise<string[]>;

  // ---- Secrets (OS keychain) ----
  /** Routes through the OS keychain (keytar) for sensitive values. */
  setSecret(key: string, value: string): Promise<void>;
  getSecret(key: string): Promise<string | undefined>;
  deleteSecret(key: string): Promise<void>;

  // ---- Settings (read-only mirror of contributes.configuration) ----
  /**
   * Read a user-edited setting defined in `contributes.configuration`. The
   * host populates these from the rendered settings form. Equivalent to
   * `get('__settings.<key>')` but type-safe against the schema.
   */
  getSetting<T = unknown>(key: string): Promise<T | undefined>;

  // ---- Per-extension SQLite database ----
  /**
   * Open a SQLite database file owned by this extension. The file lives at
   * `data/extensions/<id>/db/<name>.db`. Use this for indexes, embeddings,
   * or any data that exceeds the KV tier. Requires the `storage:database`
   * permission. The host opens the file with WAL mode and foreign keys on.
   *
   * The database is created on first open. The host runs no migrations -
   * the extension is responsible for its own schema. The host backs the
   * file up with the rest of user data unless the extension marks it
   * ephemeral via `opts`.
   */
  openDatabase(
    name: string,
    opts?: OpenDatabaseOpts,
  ): Promise<IExtensionDatabase>;

  /** Approximate disk usage of all storage owned by this extension, in bytes. */
  diskUsage(): Promise<{ kv: number; databases: number; secretsCount: number }>;

  // ---- Managed folder (desktop-only, large files) ----

  /**
   * Request a user-chosen folder for scoped file storage. The host opens a
   * folder picker dialog; if the user selects a folder the grant is persisted
   * so it survives extension restarts. Returns `null` if the user cancelled.
   * Requires the `fs:managed-folder` permission.
   *
   * @param purpose - Human-readable reason shown in the folder picker dialog.
   */
  requestFolder(purpose: string): Promise<FolderGrantHandle | null>;

  /**
   * Get the current folder grant, if one exists. Returns `null` if no grant
   * has been made or if it was revoked. Requires `fs:managed-folder`.
   */
  getFolderGrant(): Promise<FolderGrantHandle | null>;

  /**
   * Revoke the current folder grant. The files on disk are NOT deleted - only
   * the extension's access is removed. Requires `fs:managed-folder`.
   */
  revokeFolderGrant(): Promise<void>;

  /**
   * Read a file inside the granted folder. The `path` is relative to the
   * grant root and must not escape it. Requires `fs:managed-folder`.
   */
  readFile(path: string): Promise<ArrayBuffer>;

  /**
   * Write (or overwrite) a file inside the granted folder. The `path` is
   * relative to the grant root. Parent directories are created automatically.
   * Requires `fs:managed-folder`.
   */
  writeFile(path: string, data: ArrayBuffer | Uint8Array): Promise<void>;

  /**
   * Delete a file inside the granted folder. No-op if the file does not
   * exist. Requires `fs:managed-folder`.
   */
  deleteFile(path: string): Promise<void>;

  /**
   * List files and directories inside the granted folder, optionally
   * filtered by a relative path prefix. Requires `fs:managed-folder`.
   */
  listFiles(prefix?: string): Promise<FileInfo[]>;

  /**
   * Get metadata for a single file inside the granted folder. Returns `null`
   * if the file does not exist. Requires `fs:managed-folder`.
   */
  statFile(path: string): Promise<FileInfo | null>;

  /**
   * Get aggregate disk usage for the granted folder. Requires
   * `fs:managed-folder`.
   */
  getFolderUsage(): Promise<FolderUsageInfo>;
}

// --- IL10nApi *(T1)* -------------------------------------------------------

/**
 * Extension catalogs ship in `l10n/<bcp47>.json` files inside the extension
 * package. The host loads them into Spec B's `I18nService` under a namespace
 * prefixed with the extension ID, so `ext.greekTools.openLexicon` resolves to
 * the extension's own catalog.
 */
export interface IL10nApi {
  /** Resolve a localization key against the extension's catalog. */
  t(key: string, params?: Record<string, unknown>): Promise<string>;

  // Maintainer note: this was declared `currentLocale: Promise<string>`, which
  // cannot work. `api` is an RPC proxy, so reading a property yields a
  // *function* that would dispatch the call, and awaiting a function is not an
  // error - it resolves to the function. Callers following the old declaration
  // silently got a function where a locale string was promised. The host has
  // always implemented the `l10n.currentLocale` method this signature
  // describes. `ApiSurfaceContract.test.ts` now rejects bare data properties.
  /** The host's current UI locale, e.g. `'en'` or `'pt-BR'`. */
  currentLocale(): Promise<string>;
}

// --- IEventsApi *(T1)* -----------------------------------------------------

/**
 * Options for `IEventsApi.subscribe`.
 */
export interface SubscribeOptions {
  /**
   * Ordering hint for `filter` and `provider` channels. Lower runs first.
   * Clamped to `ORDER_PLUGIN_MIN..ORDER_PLUGIN_MAX` (100..1000); defaults to
   * `ORDER_DEFAULT` (500) when omitted. Ignored for `event` channels - see
   * `EXTENSION_POINT_KINDS` in `ExtensionPointTypes.ts`.
   */
  order?: number;
}

/**
 * A channel an extension may `publish` on: its own namespace, `ext.<its
 * own id>.<anything>`. Distinct from `ExtensionPointId`, the closed set of
 * host-emitted channels - this is the open set of extension-to-extension
 * broadcast channels (P1.8). The host enforces the namespace prefix at
 * `publish` time; nothing about the *type* prevents naming another
 * extension's namespace, because the id segment is only known at runtime.
 */
export type ExtensionScopedChannel = `ext.${string}.${string}`;

/**
 * Every channel `api.events.subscribe` accepts: the closed, host-emitted
 * `ExtensionPointId` vocabulary, plus the open `ext.<id>.*` namespace an
 * extension may `publish` on.
 */
export type ExtensionChannel = ExtensionPointId | ExtensionScopedChannel;

/**
 * One subscription surface for every host-emitted hook channel (see the
 * 14-member `ExtensionPointId` union and its kind/payload/return maps in
 * `ExtensionPointTypes.ts`) and for extension-to-extension broadcast
 * channels (`ext.<id>.*`, P1.8's `publish`).
 *
 * Replaces the earlier `onDid*` properties scattered across eleven
 * namespaces (the active-verse and word-selection events on `api.bible`, the
 * change event on `api.notes`, and so on) and the speculative
 * `ExtensionPointId` vocabulary that had zero call sites -
 * two systems collapsed into one channel string, one table
 * (`EXTENSION_POINT_KINDS`), and one drift test
 * (`ApiSurfaceContract.test.ts`). There is **no per-namespace subscribe
 * sugar** - `api.events.subscribe('verse.activeChanged', cb)` is the only
 * way in, deliberately: per-namespace properties are exactly what required
 * a second, hand-maintained table (the old `EVENT_PROPERTIES`) to keep in
 * sync with the first, and that drift is what this design removes.
 *
 * Dispatch semantics by kind (`EXTENSION_POINT_KINDS[channel]`):
 *
 * - **event** - fire-and-forget, parallel, the host does not await
 *   subscribers. A throw is logged and skipped.
 * - **filter** - the host calls subscribers sequentially; each may replace
 *   the payload for the next (or return `'continue'`/`'cancel'` for a
 *   cancelable filter - see `EXTENSION_POINT_CANCELABLE`). A subscriber that
 *   throws or times out is skipped, never treated as `'cancel'` - hooks fail
 *   open.
 * - **provider** - the host calls every subscriber in parallel and
 *   concatenates each one's array result, ordered by `opts.order` then by
 *   extension id.
 *
 * A channel in `EXTENSION_POINT_REPLAY` (currently only
 * `'verse.activeChanged'`) replays its current value to a subscriber
 * immediately, rather than waiting for the next change - the active verse is
 * state, not a stream, and a handler registered during `activate()` would
 * otherwise see nothing until the user next navigated.
 */
export interface IEventsApi {
  subscribe<K extends ExtensionPointId>(
    channel: K,
    handler: (
      payload: ExtensionPointPayloadMap[K],
    ) =>
      | ExtensionPointReturnMap[K]
      | void
      | Promise<ExtensionPointReturnMap[K] | void>,
    opts?: SubscribeOptions,
  ): Promise<DisposableHandle>;
  /**
   * Subscribe to another extension's broadcast channel (`ext.<its id>.*`,
   * published via that extension's own `api.events.publish`). Always
   * `event`-kind semantics: fire-and-forget, no cancel, no collect, no
   * replay. The payload type is whatever the publisher chose to send -
   * there is no host-declared shape for an extension-owned channel.
   */
  subscribe(
    channel: ExtensionScopedChannel,
    handler: (payload: unknown) => void | Promise<void>,
    opts?: SubscribeOptions,
  ): Promise<DisposableHandle>;

  /**
   * Broadcast `payload` to every other active extension subscribed to
   * `channel` (P1.8). `channel` must start with `ext.<this extension's
   * id>.` - the same structural rule `commands.register` already enforces
   * for command ids - so one extension can never speak on another's
   * namespace, and there is no free-form pub/sub bus (see
   * `Extensions/README.md`'s explicit prohibition on one). The publisher
   * never receives its own message. Resolves once every subscribed worker
   * has been sent the event; delivery itself is fire-and-forget, like any
   * other `event`-kind channel.
   */
  publish(channel: ExtensionScopedChannel, payload: unknown): Promise<void>;
}

// --- IRuntimeApi *(T1 - reverse-RPC endpoint binding)* ---------------------

/**
 * Binds extension callbacks to the reverse-RPC endpoint names the host calls
 * back on.
 *
 * **Why this exists.** Several registration DTOs carry a `handlerEndpoint`
 * string rather than a function, because a function cannot survive the RPC
 * envelope that carries the registration to the host. When the user fires the
 * command (or the host needs hover content, a decoration, a rendered display
 * mode), the host issues a *reverse* request naming that endpoint. Until this
 * namespace existed there was no way for the extension to say which of its
 * functions answers to that name, so every reverse request came back
 * `Unknown reverse RPC method` and the registration was inert:
 * `contributes.commands` entries appeared in the palette and did nothing when
 * invoked.
 *
 * ```typescript
 * exports.activate = async (api) => {
 *   await api.runtime.expose('helloWorld', async () => {
 *     await api.ui.showNotification({ key: 'greeting' });
 *   });
 * };
 * ```
 *
 * The endpoint name is the extension's own choice and is scoped to its worker;
 * two extensions may use the same name without colliding. Names beginning with
 * `runtime.` are reserved for the host.
 *
 * Prefer passing a `handler` function directly to `commands.register` where
 * that is available - it calls `expose` for you with a generated name. Use
 * this directly for endpoints named in `extension.json`, which the host may
 * call before any imperative registration has run.
 */
export interface IRuntimeApi {
  /**
   * Bind `handler` to `endpoint`. The returned handle unbinds it.
   *
   * The handler receives the reverse request's positional arguments and may
   * return a value (or a promise of one), which is sent back to the host as
   * the response. Throwing rejects the host's request.
   *
   * Binding an endpoint that is already bound replaces the previous handler.
   */
  expose(
    endpoint: string,
    handler: (...args: unknown[]) => unknown | Promise<unknown>,
  ): Promise<DisposableHandle>;

  /** Unbind an endpoint. Idempotent. */
  unexpose(endpoint: string): Promise<void>;

  /** Endpoint names currently bound by this extension. */
  listExposed(): Promise<string[]>;
}

// --- IPanelsApi *(T1 - panel iframe to worker channel)* --------------------

/**
 * The channel between an extension's panel iframes and its own worker.
 *
 * **The problem it solves.** A panel iframe is sandboxed on its own
 * `ext-ui://<extensionId>` origin and reaches the host through a deliberately
 * tiny renderer-side bridge - navigate a verse, read the theme mode, make a
 * permission-gated fetch. It cannot call `storage`, `bible`, or `l10n`,
 * because putting the `api.*` surface in the renderer would mean enforcing
 * permissions in a second place, and the renderer is the wrong place to
 * decide them. So a panel that holds state, reads scripture, or localises a
 * string had no way to do it.
 *
 * The answer is not a second API surface but an opaque channel: the panel
 * posts a message, this extension's own worker receives it and decides what to
 * do with the API access it already holds. Permission enforcement stays where
 * it is, the host surface grows by one method, and the extension author
 * controls exactly what its panel may ask for.
 *
 * ```typescript
 * // worker (main.js)
 * api.panels.onMessage(async (msg) => {
 *   if (msg.type === 'getRange') return api.bible.getRange(msg.start, msg.end);
 *   throw new Error(`unknown panel request: ${msg.type}`);
 * });
 * ```
 * ```typescript
 * // panel (ui/index.html)
 * const verses = await bible.postToWorker({ type: 'getRange', start, end });
 * ```
 *
 * **Security property:** the host resolves which worker to deliver to from the
 * closure that mounted the iframe, never from the message payload, so a panel
 * cannot name another extension and spend its grants. Payloads are size-capped
 * and requests time out; the worker is a QuickJS realm and an uncapped message
 * firehose into it would be a denial-of-service surface.
 */
export interface IPanelsApi {
  /**
   * Handle messages posted by this extension's panel iframes. The handler's
   * return value resolves the panel's `postToWorker` promise; throwing rejects
   * it with the error message.
   *
   * Registering a second handler replaces the first - there is one channel per
   * extension, not one per panel. Use a discriminator in the message if a
   * panel needs to route.
   */
  onMessage(
    handler: (message: unknown, sender: PanelMessageSender) => unknown | Promise<unknown>,
  ): Promise<DisposableHandle>;

  /**
   * Push a message to this extension's open panels, without a reply. Panels
   * receive it through `onWorkerMessage`.
   *
   * `panelId` targets one panel; omit it to broadcast to all of this
   * extension's panels.
   */
  postMessage(message: unknown, opts?: { panelId?: string }): Promise<void>;
}

/**
 * String literal union of every host-emitted extension point. Payload and
 * return types live in `ExtensionPointTypes.ts`.
 *
 * **Pruned from 40 to 14 members (task 0024, round 3, P0.3).** The union was
 * written speculatively, well ahead of any call site - `dispatchExtensionPoint`
 * had zero callers repo-wide before this round. The 26 members deleted below
 * had no host chokepoint that would ever fire them; keeping a channel nothing
 * emits is a permanent lie in the public type, indistinguishable from inside
 * an extension from an event that simply has not fired yet (the same failure
 * mode the old `onDid*` surface had). Re-adding a channel later is additive;
 * leaving dead ones in was not. Deleted:
 * `verse.beforeRender`, `verse.afterRender`, `verse.hover`,
 * `verse.contextMenu`, `verse.word.contextMenu`, `verse.decorate`,
 * `verse.beforeFormat`, `commentary.providerRegistered`,
 * `commentary.beforeShow`, `commentary.similarRequested`,
 * `dictionary.lookupRequested`, `dictionary.beforeShow`, `book.beforeShow`,
 * `notes.beforeSave`, `notes.afterSave` (replaced by `notes.changed`, which
 * matches the unified create/update/delete notification the bridge actually
 * emits), `bookmarks.afterAdd`, `search.afterResults`,
 * `search.suggestionsRequested`, `layout.presetApplied`,
 * `bible.referenceParsed`, `command.beforeExecute` (would need a
 * renderer-side dispatch proxy over `RendererCommandBridge` - `CommandRegistry.execute`
 * lives in the renderer, not the main process where `dispatchExtensionPoint`
 * runs - its own task), `app.ready` (redundant with `activationEvents`),
 * `session.restored`, `theme.changed` (no theme bridge exists yet - re-add
 * with the bridge, not before), `permissions.changed`, `module.installed`,
 * `module.updated`, `module.removed` (the module manager may grow these
 * later, but "likely" is exactly the standard that produced 40 channels and
 * 0 call sites).
 */
export type ExtensionPointId =
  // Verse
  | 'verse.activeChanged'
  | 'verse.wordSelected'
  // Notes / highlights
  | 'notes.changed'
  | 'notes.beforeDelete'
  | 'highlights.afterChange'
  // Search
  | 'search.beforeQuery'
  // Cross references
  | 'crossReferences.requested'
  // Workspace
  | 'panel.opened'
  | 'panel.closed'
  | 'panel.focused'
  // Host lifecycle
  | 'settings.changed'
  | 'locale.changed'
  | 'extension.activated'
  | 'extension.deactivated';

// --- INetworkApi *(T2)* ----------------------------------------------------

export interface INetworkApi {
  /**
   * Mediated outbound HTTP/HTTPS request. The URL's host MUST appear in the
   * extension's `network.allowedHosts` manifest entry; otherwise the call
   * rejects with `NetworkHostNotAllowedError` even if `network` permission is
   * granted.
   *
   * Private-network destinations (loopback, RFC1918, link-local) are blocked
   * by default. To target a private host, the extension must list a literal
   * IP or hostname in `allowedHosts` and the user must approve it explicitly
   * at install time (the consent dialog highlights private targets).
   */
  fetch(url: string, init?: NetworkFetchInit): Promise<NetworkFetchResponse>;

  /** True if the host is currently in the extension's allowlist. */
  isHostAllowed(host: string): Promise<boolean>;
}

// --- IAuthApi *(T2 - depends on INetworkApi)* ------------------------------

export interface IAuthApi {
  /**
   * Run the OAuth 2.0 Authorization Code flow (with PKCE by default). The
   * host opens a real BrowserWindow pointing at `authorizeUrl`, watches for
   * navigation to the redirect URI, captures the `code` and `state`, performs
   * the token exchange itself, and resolves with the result.
   *
   * The redirect URI is always `ext-ui://<extensionId>/<redirectPath>`,
   * registered with the auth provider. This means the host's custom protocol
   * receives the redirect - no public callback server required.
   *
   * Token storage is the extension's responsibility (use `storage:secrets`).
   */
  startOAuth(opts: StartOAuthOpts): Promise<OAuthResult>;

  /** Exchange a refresh_token for a new access_token. */
  refreshOAuth(opts: RefreshOAuthOpts): Promise<OAuthResult>;

  /**
   * Open the user's default browser at a URL (e.g. for a settings page on
   * the extension's website). Requires `network:oauth` permission.
   */
  openExternal(url: string): Promise<void>;
}

// --- ITasksApi *(T2)* ------------------------------------------------------

export interface ITasksApi {
  /**
   * Run a long-running task. The host invokes `workEndpoint` via reverse-RPC
   * with a `taskHandle` the worker uses to report progress and check for
   * cancellation. The host shows a progress entry in the status bar and a
   * notification on completion if `notifyOnComplete` is set.
   */
  run<T = void>(task: BackgroundTaskDescriptor): Promise<T>;

  /** Report progress for a running task. Called from inside the work handler. */
  reportProgress(taskHandle: string, update: TaskProgressUpdate): Promise<void>;

  /** True if the user has requested cancellation. The work handler should return early. */
  isCancellationRequested(taskHandle: string): Promise<boolean>;

  /** Cancel a running task by ID. */
  cancel(taskId: string): Promise<void>;

  /** List tasks owned by this extension. */
  list(): Promise<BackgroundTaskInfo[]>;
}

// --- IExtensionsApi *(T2)* -------------------------------------------------

/**
 * The narrow surface (no streaming) is intentional. If two extensions need a
 * tighter coupling, they can both depend on a third extension that owns the
 * shared state. `extension.activated`/`extension.deactivated`
 * (`api.events.subscribe`) cover the one pair of events this namespace used
 * to carry as direct properties before task 0024 round 3's event unification.
 */
export interface IExtensionsApi {
  /**
   * Call a method another extension has exported via `contributes.apiExports`.
   * Requires `extensions:call` permission. The host validates the call against
   * the callee's manifest - undeclared methods reject with
   * `ApiExportNotFoundError`.
   *
   * Calls are mediated by the host (worker A -> host -> worker B) so neither
   * extension can crash the other. Arguments and return values must be
   * JSON-serializable.
   */
  call<T = unknown>(
    extensionId: string,
    method: string,
    args?: unknown[],
  ): Promise<T>;

  /** True if an extension is installed and active. */
  isActive(extensionId: string): Promise<boolean>;

  /** List extensions that export at least one API method. */
  listProviders(): Promise<ExtensionProviderInfo[]>;
}

// --- IAiApi (RESERVED) *(T1 stub - full surface is T3)* --------------------

/**
 * RESERVED in v1. The permission slot, manifest field, and provider role
 * (`aiAssistant`) exist so extensions and the host can plan around AI
 * integration without breaking the API contract later. The host UI for
 * "Ask AI about this verse" lives in a follow-up spec.
 *
 * Extensions that want to ship AI features in v1 should use `INetworkApi` to
 * call their own AI backend; the only thing missing is the host's built-in
 * panel for displaying AI responses.
 */
export interface IAiApi {
  /** True if the host has any active AI provider. Always false in v1. */
  isAvailable(): Promise<boolean>;
}
