/**
 * Study Overview Provider
 *
 * Fetches pre-generated study overview data for an entire chapter in a single
 * request, then serves per-verse data from the in-memory cache. This replaces
 * multiple per-verse round-trips for commentary overviews, topics, cross-refs,
 * and tag graph entities.
 *
 * The server endpoint GET /api/study/overview/:book/:chapter returns pre-computed
 * data from the study-cache.db generated by scripts/generate-study-cache.js.
 */

import { isDigestModule, getDigestDisplayName } from '../moduleDescriptions';
import type {
  CrossRefGroupData,
  CrossRefEntryData,
  VerseTopicData,
  TagGraphEntityData,
  CommentaryHomeData,
  CommentaryHomeModule,
} from '../types';

// ── Compact cache shapes (matching generate-study-cache.js output) ──

interface CachedCommentaryEntry {
  m: string;   // module abbreviation
  mn: string;  // module name
  s: number;   // verse_id_start
  e: number;   // verse_id_end
  l: string;   // entry_level
  w: number;   // word_count
}

interface CachedTopic {
  id: number;
  n: string;          // name
  p?: string;         // parent chain string ("Doctrine > Soteriology")
  /**
   * Ancestors root-first as `[topicId, name, recursiveVerseCount]`. Absent in
   * caches generated before the field existed — hence the `p`-only fallback
   * in {@link StudyOverviewProvider.getTopicsForVerse}.
   */
  a?: [number, string, number][];
  vc: number;         // recursive verse count
  src: string;        // source abbreviation
  sn: string;         // source name
  d?: string;         // description
}

interface CachedCrossRefGroup {
  src: string;        // source module abbreviation
  g: {
    id: number;       // group_id
    ph?: string;      // phrase
    so: number;       // sort_order
  };
  e: Array<{
    tv: number;       // target_verse_id
    tve?: number;     // target_verse_end_id
    n?: string;       // note
    so: number;       // sort_order
  }>;
}

interface CachedEntity {
  eid: string;        // entity_id
  cat: string;        // category
  n: string;          // name
  eve?: number;       // end_verse_id
  src?: string;       // source
}

interface StudyOverviewResponse {
  commentary: CachedCommentaryEntry[];
  topics: Record<string, CachedTopic[]>;
  crossrefs: Record<string, CachedCrossRefGroup[]>;
  entities: Record<string, CachedEntity[]>;
  cached: boolean;
}

interface ChapterCache {
  data: StudyOverviewResponse;
  fetchedAt: number;
}

export interface IStudyOverviewProvider {
  /**
   * Ensure study overview data is loaded for a chapter.
   * Returns immediately if already cached.
   */
  loadChapter(book: number, chapter: number): Promise<void>;

  /** Get commentary home data for a specific verse from the cached chapter data. */
  getCommentaryHomeForVerse(book: number, chapter: number, verse: number): CommentaryHomeData;

  /** Get topics for a specific verse from the cached chapter data. */
  getTopicsForVerse(book: number, chapter: number, verseId: number): VerseTopicData[];

  /** Get cross-reference groups for a specific verse from the cached chapter data. */
  getCrossRefsForVerse(book: number, chapter: number, verseId: number): CrossRefGroupData[];

  /** Get tag graph entities for a specific verse from the cached chapter data. */
  getEntitiesForVerse(book: number, chapter: number, verseId: number): TagGraphEntityData[];

  /** Whether the cache has data for this chapter. */
  hasChapter(book: number, chapter: number): boolean;

  /** Whether the cache is available (server returned cached: true). */
  isCacheAvailable(): boolean;
}

export class StudyOverviewProvider implements IStudyOverviewProvider {
  private cache = new Map<string, ChapterCache>();
  private pending = new Map<string, Promise<void>>();
  private _cacheAvailable: boolean | null = null;
  /** Set to true once the server reports cached:false — stops further fetches. */
  private _serverHasNoCache = false;

  constructor(private baseUrl: string) {}

  private cacheKey(book: number, chapter: number): string {
    return `${book}-${chapter}`;
  }

  async loadChapter(book: number, chapter: number): Promise<void> {
    const key = this.cacheKey(book, chapter);

    // Already cached
    if (this.cache.has(key)) return;

    // Server already told us it has no study cache — skip further fetches
    if (this._serverHasNoCache) return;

    // Already loading — wait for the in-flight request
    if (this.pending.has(key)) {
      return this.pending.get(key);
    }

    const promise = this._fetchChapter(book, chapter, key);
    this.pending.set(key, promise);
    try {
      await promise;
    } finally {
      this.pending.delete(key);
    }
  }

  private async _fetchChapter(book: number, chapter: number, key: string): Promise<void> {
    try {
      const res = await fetch(`${this.baseUrl}/api/study/overview/${book}/${chapter}`);
      if (!res.ok) return;
      const data: StudyOverviewResponse = await res.json();
      this._cacheAvailable = data.cached;
      if (data.cached) {
        this.cache.set(key, { data, fetchedAt: Date.now() });
      } else {
        // Server has no study cache DB — stop trying for all chapters
        this._serverHasNoCache = true;
      }
    } catch {
      // Network error — leave cache empty, fallback to per-verse providers
    }
  }

  hasChapter(book: number, chapter: number): boolean {
    return this.cache.has(this.cacheKey(book, chapter));
  }

  isCacheAvailable(): boolean {
    return this._cacheAvailable === true;
  }

  // ── Commentary home data ───────────────────────────────────────────

  getCommentaryHomeForVerse(book: number, chapter: number, verse: number): CommentaryHomeData {
    const cached = this.cache.get(this.cacheKey(book, chapter));
    if (!cached) return { verseModules: [], chapterModules: [] };

    const verseId = book * 1000000 + chapter * 1000 + verse;
    const entries = cached.data.commentary;

    // Group entries by module, categorize by level relative to this verse
    const verseModules = new Map<string, CommentaryHomeModule>();
    const passageModules = new Map<string, CommentaryHomeModule>();
    const chapterModules = new Map<string, CommentaryHomeModule>();

    for (const entry of entries) {
      const coversVerse = entry.s <= verseId && entry.e >= verseId;
      if (!coversVerse) continue;

      const isVerse = entry.l === 'verse' && entry.s === verseId;
      const isPassage = !isVerse && (entry.l === 'passage' || (entry.e !== entry.s));
      const isChapter = entry.l === 'chapter' || entry.l === 'book';

      const mod: CommentaryHomeModule = {
        moduleAbbr: entry.m,
        // The digest ships under the name "SYNTHESIS"; readers know it as
        // "Combined Summary". Resolved at the source so every card, header and
        // back-bar built from this list says the same thing.
        moduleName: isDigestModule(entry.m) ? getDigestDisplayName() : entry.mn,
        wordCount: entry.w,
      };

      if (isVerse) {
        const existing = verseModules.get(entry.m);
        if (existing) {
          existing.wordCount += entry.w;
        } else {
          verseModules.set(entry.m, mod);
        }
      } else if (isPassage) {
        if (!verseModules.has(entry.m)) {
          const existing = passageModules.get(entry.m);
          if (existing) {
            existing.wordCount += entry.w;
          } else {
            passageModules.set(entry.m, mod);
          }
        }
      } else if (isChapter) {
        if (!verseModules.has(entry.m) && !passageModules.has(entry.m)) {
          const existing = chapterModules.get(entry.m);
          if (existing) {
            existing.wordCount += entry.w;
          } else {
            chapterModules.set(entry.m, mod);
          }
        }
      }
    }

    return {
      verseModules: [...verseModules.values()].sort((a, b) => a.moduleName.localeCompare(b.moduleName)),
      passageModules: passageModules.size > 0 ? [...passageModules.values()].sort((a, b) => a.moduleName.localeCompare(b.moduleName)) : undefined,
      chapterModules: [...chapterModules.values()].sort((a, b) => a.moduleName.localeCompare(b.moduleName)),
    };
  }

  // ── Topics ─────────────────────────────────────────────────────────

  getTopicsForVerse(_book: number, _chapter: number, verseId: number): VerseTopicData[] {
    const key = this.cacheKey(_book, _chapter);
    const cached = this.cache.get(key);
    if (!cached) return [];

    const topics = cached.data.topics[String(verseId)];
    if (!topics) return [];

    return topics.map(t => {
      // `a` carries the ancestor ids; `p` is only a display string. A cache
      // predating `a` yields id-less ancestors, which the UI must render as
      // plain text — opening one would request topic 0 and fail.
      const ancestors = t.a
        ? t.a.map(([topic_id, name, verse_count]) => ({ topic_id, name, verse_count }))
        : (t.p ? t.p.split(' > ') : []).map(name => ({ topic_id: 0, name, verse_count: 0 }));
      const parent = ancestors.length > 0 ? ancestors[ancestors.length - 1] : undefined;
      return {
        topic_id: t.id,
        parent_topic_id: parent && parent.topic_id > 0 ? parent.topic_id : null,
        parent_name: t.p ?? (ancestors.length > 0 ? ancestors.map(a => a.name).join(' > ') : undefined),
        ancestors,
        name: t.n,
        description: t.d ?? null,
        source_abbreviation: t.src,
        source_name: t.sn,
        verse_count: t.vc,
      };
    });
  }

  // ── Cross-references ───────────────────────────────────────────────

  getCrossRefsForVerse(_book: number, _chapter: number, verseId: number): CrossRefGroupData[] {
    const key = this.cacheKey(_book, _chapter);
    const cached = this.cache.get(key);
    if (!cached) return [];

    const groups = cached.data.crossrefs[String(verseId)];
    if (!groups) return [];

    return groups.map(g => ({
      group: {
        group_id: g.g.id,
        verse_id: verseId,
        phrase: g.g.ph ?? null,
        sort_order: g.g.so,
      },
      entries: g.e.map((e, i) => ({
        entry_id: i,  // not stored in cache
        group_id: g.g.id,
        target_verse_id: e.tv,
        target_verse_end_id: e.tve ?? null,
        note: e.n ?? null,
        sort_order: e.so,
      } as CrossRefEntryData)),
    }));
  }

  // ── Tag graph entities ─────────────────────────────────────────────

  getEntitiesForVerse(_book: number, _chapter: number, verseId: number): TagGraphEntityData[] {
    const key = this.cacheKey(_book, _chapter);
    const cached = this.cache.get(key);
    if (!cached) return [];

    const entities = cached.data.entities[String(verseId)];
    if (!entities) return [];

    return entities.map(e => ({
      entity_id: e.eid,
      category: e.cat,
      name: e.n,
      source: e.src,
    }));
  }
}
