/** Shared sync primitives (contracts 0063 §1). Browser-safe: no Node imports, no top-level side effects. */
import type { KdfParamsJson } from '../Crypto';

/** 16 random bytes as 32 lowercase hex chars. Account ids, record ids, device ids (device: 8 bytes / 16 hex). */
export type HexId = string;
export type AccountId = HexId;   // 32 hex, generated by the client at sign-up
export type RecordId = HexId;    // 32 hex; random, or derived (deriveRecordId) for natural-key records
export type DeviceId = string;   // 16 hex

/**
 * Hybrid logical clock, fixed width so string comparison == causal order:
 * `${ms 12 hex}:${counter 4 hex}:${deviceId 16 hex}` e.g. "0192f3a1b2c3:0000:9f3c0a1b2c3d4e5f".
 */
export type HlcString = string;

/** Record types. Core tables use their table name; extension and file records use these prefixes. */
export type RecordType =
  | 'user_commentary' | 'user_note' | 'note_verse_link' | 'content_verse_link' | 'verse_link'
  | 'user_text_markup' | 'user_cross_reference' | 'collection' | 'pinned_item'
  | 'reading_plan' | 'reading_plan_day' | 'reading_plan_passage' | 'user_reading_progress'
  | 'prayer_item' | 'prayer_update' | 'journal_entry' | 'user_data_item'
  | 'ext.kv' | 'ext.db' | 'bn.file';

/** Decrypted content of one record (the JSON inside the envelope, before padding). */
export interface RecordPlaintext {
  /** Record type. Unknown types MUST be kept opaque by readers, never dropped or deleted. */
  t: RecordType | string;
  /** Codec version of `d` for this type (starts at 1). A reader seeing a higher version keeps the record opaque. */
  cv: number;
  h: HlcString;
  /** Writing device. */
  dev: DeviceId;
  /** Type-specific payload; foreign keys are RecordIds, never local ids. */
  d: Record<string, unknown>;
}

/** What the server stores and returns per record. */
export interface EncryptedRecord {
  id: RecordId;
  seq: number;          // server-assigned, strictly increasing per account
  deleted: boolean;     // tombstone: blob is null
  blob: Uint8Array | null;
}

export type { KdfParamsJson };
