import { useState, useEffect } from 'preact/hooks';
import { useTranslation } from 'react-i18next';
import { useVersePopup } from '../../hooks/useVersePopup';
import { commentaryStore } from '../../stores/commentaryStore';
import { studyStore } from '../../stores/studyStore';
import { useStore } from '../../hooks/useStore';
import { DIGEST_MODULE_ABBR, getDigestDisplayName } from '../../moduleDescriptions';
import { DigestDisclaimer } from '../CommentaryPane/DigestDisclaimer';
import { renderMarkdownToHtml } from '../../utils/markdownRenderer';
import { sanitizeHtml } from '../../utils/sanitize';
import { processCommentaryLinks } from '../../../../../packages/core/src/Services/CommentaryLinkProcessor';
import { StudySection } from './StudySection';
import type { IBibleDataProvider } from '../../providers/interfaces';
import type { CommentaryEntryData } from '../../types';

interface StudySynthesisProps {
  bibleProvider?: IBibleDataProvider;
}

export function StudySynthesis({ bibleProvider }: StudySynthesisProps) {
  const { t } = useTranslation();
  const verseId = useStore(studyStore, () => studyStore.verseId);
  const book = useStore(studyStore, () => studyStore.book);
  const chapter = useStore(studyStore, () => studyStore.chapter);

  const [entries, setEntries] = useState<CommentaryEntryData[]>([]);
  const [loading, setLoading] = useState(false);
  const [loaded, setLoaded] = useState(false);

  const { containerProps: versePopupProps, popupJsx: versePopupJsx } = useVersePopup(bibleProvider);

  // Fetch SYNTHESIS entries when verse changes
  useEffect(() => {
    if (!book || !chapter) {
      setEntries([]);
      setLoaded(false);
      return;
    }

    let cancelled = false;
    setLoading(true);

    commentaryStore.fetchModuleEntries(DIGEST_MODULE_ABBR, book, chapter).then(chapterEntries => {
      if (cancelled) return;
      // Filter to current verse
      const filtered = verseId
        ? chapterEntries.filter(e =>
            e.verse_id_start <= verseId &&
            (e.verse_id_end ? e.verse_id_end >= verseId : e.verse_id_start === verseId)
          )
        : [];
      setEntries(filtered);
      setLoading(false);
      setLoaded(true);
    }).catch(() => {
      if (!cancelled) {
        setEntries([]);
        setLoading(false);
        setLoaded(true);
      }
    });

    return () => { cancelled = true; };
  }, [verseId, book, chapter]);

  // Don't render anything if no content (or still loading initial)
  if (!loaded || (!loading && entries.length === 0)) return null;

  const contentFormat = commentaryStore.getContentFormat(DIGEST_MODULE_ABBR);

  const handleOpenInCommentary = () => {
    commentaryStore.openTemporaryTab(DIGEST_MODULE_ABBR, getDigestDisplayName());
    commentaryStore.setRightPaneMode('commentary');
  };

  return (
    <StudySection id="synthesis" label={t('studySynthesis.title')} defaultExpanded={false}>
      {loading ? (
        <div class="study-crossrefs__loading">
          <i class="fa-solid fa-spinner fa-spin" style={{ marginRight: '6px' }} />{t('studySynthesis.loading')}
        </div>
      ) : (
        <div class="study-synthesis">
          <DigestDisclaimer collapsedLabel={t('digestDisclaimer.autoGeneratedNotice')} />
          <div class="study-synthesis__entries" {...versePopupProps}>
            {entries.map(entry => {
              const htmlContent = contentFormat === 'markdown'
                ? renderMarkdownToHtml(entry.content)
                : entry.content;
              const linkedContent = processCommentaryLinks(htmlContent, {
                bookNumber: book!,
                chapter: chapter!,
              });
              return (
                <div key={entry.entry_id} class="commentary-entry__text" dangerouslySetInnerHTML={{ __html: sanitizeHtml(linkedContent) }} />
              );
            })}
            {versePopupJsx}
          </div>
          <button class="study-synthesis__open-btn" onClick={handleOpenInCommentary}>
            <i class="fa-solid fa-arrow-up-right-from-square fa-xs" /> {t('studySynthesis.openInCommentary')}
          </button>
        </div>
      )}
    </StudySection>
  );
}
